<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllFlowActionTable extends UllRecordTable
{

  /**
   * Returns the action_id for a given slug
   * 
   * @param string $slug
   * @return integer
   *
   */
  public static function findIdBySlug($slug)
  {
    $ullFlowAction = Doctrine::getTable('UllFlowAction')->findOneBySlug($slug);
    if ($ullFlowAction)
    {
      return $ullFlowAction->id;
    }
  }
  
  /**
   * Find by Id
   *
   * @param integer $id
   * @return Doctrine_Record
   */  
  public static function findById($id)
  {
    $q = new Doctrine_Query;
    $q
      ->from('UllFlowAction')
      ->where('id = ?', $id)
      ->useResultCache(true)
    ;
    
    return $q->execute()->getFirst();
  }
  
  /**
   * Check if the given action slug is not a status-only action
   *
   * @param unknown_type $slug
   * @return unknown
   */
  public static function isNonStatusOnly($slug)
  {
    if ($slug)
    {
      $action = Doctrine::getTable('UllFlowAction')->findOneBySlug($slug);
      
      if ($action)
      {
        return $action->is_status_only ? false : true;
      }
    }
  }
  
}
