<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllFlowValueTable extends UllRecordTable
{

  public static function findByDocIdAndSlug($ullFlowDocId, $slug)
  {
    
    if (!UllFlowDocTable::hasId($ullFlowDocId))
    {
      throw new InvalidArgumentException('Invalid ull_flow_doc_id given: ' .  $ullFlowDocId);
    }
    
    if (!UllFlowDocTable::hasVirtualColumn($ullFlowDocId, $slug))
    {
      throw new InvalidArgumentException('Invalid UllFlowColumnConfig->slug given: ' .  $slug);
    }
    
    $q = new Doctrine_Query;
    $q
      ->select('v.value')
      ->from('UllFlowValue v, v.UllFlowDoc d, v.UllFlowColumnConfig cc')
      ->where('d.id = ?', $ullFlowDocId)
      ->addWhere('cc.slug = ?', $slug)
    ;
//    var_dump($q->getQuery());
//    var_dump($q->getParams());
    return $result = $q->execute()->getFirst();
  }
    
}