<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllFlowAction extends BaseUllFlowAction
{

  /**
   * To string
   *
   * @return string
   */
  public function __toString()
  {
    return (string) $this->label;
  }
  
  /**
   * Calculates app icon path
   *
   * @param integer $width
   * @param integer $height
   * @return string
   */
  public function getIconPath($width = 16, $height = 16)
  {
    return '/ullFlowTheme' .
      sfConfig::get('app_theme_package', 'NG') .
      'Plugin/images/ull_flow_action_icons/' .
      $this->slug .
      '_' . $width . 'x' . $height . '.png'
    ;
  }  
  

  /**
   * Create a custom slug name using underscores
   * 
   * @param string $string
   * 
   * @return string
   */
  public static function sluggify($string)
  {
    $string = Doctrine_Inflector::urlize($string);
    $string = str_replace('-', '_', $string);
    
    return $string;
  }
  
}