<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllFlowStepAction extends BaseUllFlowStepAction
{
  
//  public function setUp()
//  {
//    parent::setUp();
//    
//    // 
//    $this->setAttribute(Doctrine::ATTR_AUTO_ACCESSOR_OVERRIDE, false);
//  }

}