<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllFlowApp extends BaseUllFlowApp
{
  
  /**
   * return the app's label
   *
   * @return string
   */
  public function __toString()
  {
    return $this->label;
  }
  
  /**
   * Get the first UllFlowStep
   *
   * @return UllFlowStep
   */
  public function findStartStep()
  {
    $q = new Doctrine_Query;
    $q->from('UllFlowStep s')
      ->where('s.ull_flow_app_id = ?', $this->id)
      ->addWhere('s.is_start = ?', true)
    ;
    return $q->execute()->getFirst();
  }
  
  /**
   * returns UllFlowStep for a given slug and for the current UllFlowApp
   *
   * @param string $slug  a UllFlowStep slug
   * @return UllFlowStep
   */
  public function findStepBySlug($slug)
  {
    $q = new Doctrine_Query;
    $q->from('UllFlowStep s')
      ->where('s.ull_flow_app_id = ?', $this->id)
      ->addWhere('s.slug = ?', $slug)
    ;
    return $q->execute()->getFirst();
  }
  
  /**
   * returns the ull_flow_step_id for a given slug and for the current UllFlowApp
   *
   * @param string $slug  a UllFlowStep slug
   * @return integer
   */
  public function findStepIdBySlug($slug)
  {
    $step = $this->findStepBySlug($slug);
    
    if ($step)
    {
      return $step->id;
    }
  }  
  
  /**
   * Calculates app icon path
   *
   * @param integer $width
   * @param integer $height
   * @return string
   */
  public function getIconPath($width = 16, $height = 16)
  {
    return '/ullFlowTheme' .
      sfConfig::get('app_theme_package', 'NG') .
      'Plugin/images/ull_flow_app_icons/' .
      $this->slug .
      '_' . $width . 'x' . $height . '.png'
    ;
  }

}