<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllFlowStepActionTable extends UllRecordTable
{

  public static function findUllFlowActionsByStep($ullFlowStepId)
  {
    $q = new Doctrine_Query;
    
    $q
      ->from('UllFlowStepAction sa')
      ->where('sa.ull_flow_step_id = ?', $ullFlowStepId)
      ->orderBy('sa.sequence, id')
    ;
    
    return $q->execute();
  }
  
}