<?php

/**
 * PluginUllFlowAppAccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllFlowAppAccessTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllFlowAppAccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllFlowAppAccess');
    }
}