<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllFlowApp extends BaseUllFlowApp
{
  
  /**
   * return the app's label
   *
   * @return unknown
   */
  public function __toString()
  {
    return $this->label;
  }

}