<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllFlowActionTable extends UllRecordTable
{

  /**
   * Returns the action_id for a given slug
   * 
   * @param string $slug
   * @return integer
   *
   */
  public static function findIdBySlug($slug)
  {
    $ullFlowAction = Doctrine::getTable('UllFlowAction')->findOneBySlug($slug);
    if ($ullFlowAction)
    {
      return $ullFlowAction->id;
    }
  }
  
}
