<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllFlowAction extends BaseUllFlowAction
{

  /**
   * To string
   *
   * @return string
   */
  public function __toString()
  {
    return $this->label;
  }
  
}