<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllFlowDocTable extends UllRecordTable
{
  /**
   * Returns ullFlowDocs in danger of due date expiration. The
   * 'danger interval' is given in days, i.e. all ullFlowDocs with
   * a due date before [today + x days] are returned.
   * 
   * By default only active tickets are returned.
   * 
   * @param int $daysBefore danger interval
   * @param boolean $onlyActive if true, only active tickets are returned
   * @return Doctrine_Collection ullFlowDocs in danger of expiration
   */
  public static function findDueDateDangerDocs($daysBefore = 2, $onlyActive = true)
  {
    if (!is_numeric($daysBefore))
    {
      throw new InvalidArgumentException('daysBefore must be numeric');
    }
    
    //use 'today' because we want docs to be overdue
    //at the end of their due date (e.g. a due date of
    //"2010-10-10" means notify at "2010-10-11 00:00:00")
    $dateThreshold = strtotime('+' . $daysBefore . ' day', strtotime('today'));
    
    $q = new Doctrine_Query();
    $q
      ->from('UllFlowDoc d')
      //so mysql only it hurts kittens
      ->where('d.due_date < ?', date('Y-m-d', $dateThreshold))
    ;
    
    //TODO: replace this with a separate flag?
    if ($onlyActive)
    {
      $q->addWhere('d.UllFlowAction.is_in_resultlist = ?', true);
    }
    
    return $q->execute();
  }

  /**
   * Retrieves all overdue (due date < now) ullFlowDocs.
   * 
   * By default only active tickets are returned.
   * 
   * @param boolean $onlyActive if true, only active tickets are returned
   * @return Doctrine_Collection expired ullFlowDocs 
   */
  public static function findOverdueDocs($onlyActive = true)
  {
    return self::findDueDateDangerDocs(0, $onlyActive);
  }
  
  /**
   * adds access checks to the query
   * 
   * @param Doctrine_Query $q
   * @param $app empty or a UllFlowApp
   * @return Doctrine_Query
   * @throws InvalidArgumentException
   */
	public static function queryAccess(Doctrine_Query $q, $app)
	{
		if ($app)
		{
		  if(!$app instanceof UllFlowApp)
		  {
		    throw new InvalidArgumentException('Please supply a valid UllFlowApp');
		  }
		}
		
    // masteradmin
    if (UllUserTable::hasGroup('MasterAdmins'))
    {
      return $q;
    }
    
    // app-specific global read access
    if ($app)
    {
      if (UllUserTable::hasPermission('UllFlow_' . $app->slug . '_global_read'))
      {
        return $q;
      }
    }
    
  	$userId = sfContext::getInstance()->getUser()->getAttribute('user_id');
  	
  	// check is_public
  	if (!$userId)
  	{
  	  $q->addWhere('x.UllFlowApp.is_public = ?', true);
  	  
  	  return $q;
  	}

  	//normal access check
  	
    // assigned to
    $q->leftJoin('x.UllEntity e');
    $q->leftJoin('e.UllEntityGroupsAsGroup aeg');
    
    // memory:
    $q->leftJoin('x.UllFlowMemories m');
    $q->leftJoin('m.CreatorUllEntity.UllEntityGroupsAsGroup meg');
    
    // global read access:
    $q->leftJoin('x.UllFlowApp.UllPermission p');
    $q->leftJoin('p.UllGroup.UllUser gru');

    
    // moved all where clauses into one statement to properly set the braces
    $q->addWhere('
      e.id = ? 
      OR aeg.ull_entity_id = ? 
      OR m.creator_ull_entity_id = ? 
      OR meg.ull_entity_id = ?
      OR gru.id = ? AND p.slug LIKE ?
      OR x.UllFlowApp.is_public = ?',
      array($userId, $userId, $userId, $userId, $userId, '%_global_read', true)
    );

    return $q;
	}
	
	/**
	 * Check if a given UllFlowDoc id exists
	 * 
	 * @param integer $id    UllFlowDoc->id
	 * @return boolean
	 */
	public static function hasId($id)
	{
	  $q = new Doctrine_Query;
	  $q->from('UllFlowDoc d');
	  $q->where('d.id = ?', $id);
	  
	  return (bool) $q->count();
	}
	
	/**
	 * Check if a given virtual column exists
	 * 
	 * @param integer $id    UllFlowDoc->id
	 * @param string $slug   UlLFlowColumnConfig->slug
	 * @return boolean
	 */
	public static function hasVirtualColumn($id, $slug)
	{
    $q = new Doctrine_Query;
    $q
      ->from('UllFlowDoc d, d.UllFlowApp a, a.UllFlowColumnConfigs c')
      ->where('d.id = ?', $id)
      ->addWhere('c.slug = ?', $slug)
    ;
    
    return (bool) $q->count();
	}
	
	/**
	 * Find docs by app slug
	 * 
	 * @param string $slug
	 * @return Doctrine_Collection
	 */
	public static function findByAppSlug($slug)
	{
	   $q = new UllQuery('UllFlowDoc');
	   $q
	     ->addWhere('UllFlowApp.slug = ?', $slug)
     ;

	   return $q->execute();
	}
}