<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllFlowColumnConfig extends BaseUllFlowColumnConfig
{

  /**
   * Create a save slug name.
   * 
   * This needs to be a valid php object method name, because it is handled
   * by doctrine record filter.
   * 
   * @param string $string
   * 
   * @return string
   */
  public static function sluggify($string)
  {
    $string = Doctrine_Inflector::urlize($string);
    $string = Doctrine_Inflector::classify($string);
    
    return $string;
  }
  
}