<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllFlowAppTable extends Doctrine_Table
{
  
  /**
   * find by slug
   *
   * @param string $slug
   * @return mixed
   */
  public static function findBySlug($slug)
  {
    if (!is_string($slug))
    {
      throw new InvalidArgumentException('slug must be a string: ' . $slug);
    }
    $q = new Doctrine_Query;
    $q
      ->from('UllFlowApp')
      ->where('slug = ?', $slug)
    ;
    return $q->execute()->getFirst();
  }

}