<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllFlowAppTable extends Doctrine_Table
{
  
  /**
   * find by slug
   *
   * @param string $slug
   * @return mixed
   */
  public static function findBySlug($slug)
  {
    if (!is_string($slug))
    {
      throw new InvalidArgumentException('slug must be a string: ' . $slug);
    }
    $q = new Doctrine_Query;
    $q
      ->from('UllFlowApp')
      ->where('slug = ?', $slug)
    ;
    
    return $q->execute()->getFirst();
  }
  
  
  /**
   * Find by Id
   *
   * @param integer $id
   * @return Doctrine_Record
   */  
  public static function findById($id)
  {
    $q = new Doctrine_Query;
    $q
      ->from('UllFlowApp')
      ->where('id = ?', $id)
      ->useResultCache(true)
    ;
    
    return $q->execute()->getFirst();
  }
  
  
  /**
   * Find all apps ordered by name
   * 
   * @return Doctrine_Collection
   */
  public static function findAllOrderByName() 
  {
    $q = new UllQuery('UllFlowApp');
    $q
      ->addSelect('Translation->label')
      ->addSelect('Translation->doc_label')
      ->addSelect('slug')
      ->addOrderBy('Translation->label')
      ->addWhere('Translation->lang = ?', 
        substr(sfContext::getInstance()->getUser()->getCulture(), 0, 2))
    ;
      
    $result = $q->execute();

    return $result;
  }

}