<?php
// auto-generated by sfPropelCrud
// date: 2007/11/13 09:04:50
?>
<?php //use_helper('Object') ?>

<?php echo $sf_data->getRaw('breadcrumbTree')->getHtml() ?>


<form name="form1" id="ull_wiki_form" method="post" action="ullWiki/update">


<?php echo object_input_hidden_tag($ullwiki, 'getId'); ?>
<?php echo object_input_hidden_tag($ullwiki, 'getDocid'); ?>
<?php echo object_input_hidden_tag($ullwiki, 'getEditCounter'); ?>
<?php echo object_input_hidden_tag($ullwiki, 'getCreatorUserID'); ?>
<?php echo object_input_hidden_tag($ullwiki, 'getCreatedAT'); ?>

<?php echo input_hidden_tag('save_mode'); // saveonly, saveshow, ... ?>

<?php //echo input_hidden_tag('return_url', $return_url); ?>  
<?php echo input_hidden_tag('return_var', $return_var); ?>    


<table class='ull_wiki_edit'>
<tbody>
<tr>
  <td><b><?php echo __('Language', null, 'common'); ?>:</b></td>
  <td>
    <?php 
      //weflowTools::printR($cultures); 
/*
      echo object_select_tag($sf_data->getRaw('cultures'), 'getUllCultureId');
      //                                                       \________/
      //                                                           v 
      //                                                 =Model peer class name
*/
    ?>
  </td>

</tr>
<tr class='odd'>
  <td><b><?php echo __('Subject', null, 'common'); ?>:</b></td>
  <td><?php echo object_input_tag($ullwiki, 'getSubject', array (
  'size' => 50
)); ?></td>
</tr>

<tr>
  <td><b><?php echo __('Text', null, 'common'); ?>:</b></td>
  <td><?php 

  echo object_textarea_tag($sf_data->getRaw('ullwiki'), 'getBody', array (
  'rich' => 'fck', 'size' => '80x40', 'config' => '../ullWikiPlugin/js/FCKeditor_config.js'
))

?></td>
</tr>

<tr class='odd'>
  <td><b><?php echo __('Changelog comment', null, 'common'); ?>:</b></td>
  <td><?php echo object_input_tag($ullwiki, 'getChangelogComment', array (
  'size' => 50
)) ?></td>
</tr>

  <tr>
    <td><b><?php echo __('Tags') . ':'; ?></b></td>
    <td>
      <?php
        $tags_out = sfContext::getInstance()->getRequest()->getParameter('tags');
        if (!$tags_out) {
          //$tags = $sf_data->getRaw('ullwiki')->getTags(); //TODO
          $tags = Array();
          $tags_out = implode(', ', array_keys($tags));
        }
//        ullCoreTools::printR($tags);
        
        echo input_tag('tags', $tags_out, 'size=80'); 
        //$tags_pop = TagPeer::getPopulars(); //TODO
        $tags_pop = Array();
//        ullCoreTools::printR($tags);
        sfLoader::loadHelpers(array('Tags'));
        echo '<br />' . __('Popular tags') . ':';
        echo tag_cloud($tags_pop, 'addTag("%s")', array('link_function' => 'link_to_function'));
//        echo '<a href="#" onclick="addTag(\'dumm\')">add</a>';
        echo ull_js_add_tag();
      ?>
    </td>
  </tr>  

</tbody>
</table>
<br />


<div class='action_buttons_edit'>
<fieldset>
  <legend><?php echo __('Actions', null, 'common') ?></legend>
  
  <div class='action_buttons_edit_left'>

    <ul>


		  <li>
	    <?php 
	      echo input_tag('save', __('Save and show', null, 'common'), array(
	        'type'      => 'button',
	        'onclick'   => 'setSaveMode("saveshow");'
	      )); ?>
	    </li>
      <li>
        <input type="submit" name="commit" value="<? echo __('Save and close', null, 'common') ?>" />
      </li>

    </ul>

  </div>    

  <div class='action_buttons_edit_right'>

    <ul>

      <li>
        <?php 
          echo ull_link_to_function(
            __('Save only', null, 'common')
            , 'setSaveMode("saveonly");'
          ); 
        ?>
      </li>

      <li>
		    <?php
          echo ull_link_to(
            __('Cancel', null, 'common') 
            , $refererHandler->getReferer('edit')
            , 'ull_js_observer_confirm=true'
          );
		    ?>
      </li>
      <li>
		    <?php if ($ullwiki->getId()): ?>    
		      <?php 
		        echo link_to(
		          __('Delete', null, 'common'), 
		          'ullWiki/delete?docid='.$ullwiki->getDocid(), 
		          'confirm='.__('Are you sure?', null, 'common')
		          ); 
		      ?>
		    <?php endif; ?>
      </li>

    </ul>

  </div>

  <div class="clear"></div>  

</fieldset>

</div>


</form>

<?php
  echo javascript_tag('
    function setSaveMode(mode) {
      document.form1.save_mode.value = mode;
      document.form1.submit();
    }
  ');

  echo ull_js_observer("ull_wiki_form");
//  ullCoreTools::printR($ull_form);
?>
