<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllWikiTable extends UllRecordTable
{

  public static function setOldDocsDeleted($docid) 
  {
    $q = new Doctrine_Query;
    /*
    $q->delete('UllWiki w')
      ->from('UllWiki w')
      ->where('w.docid = ?', $docid)
      ->execute() #??strange
    ;*/
    $q->update('UllWiki w')
      ->set('deleted', '1')
      ->where('w.docid = ?', $docid)
      ->execute()
    ;
  }

  public static function getNextFreeDocid() 
  {

    $q = new Doctrine_Query;
    $q->from('UllWiki w')
      ->orderBy('w.docid DESC')
      ->limit(1)
    ;
    $ullwiki = $q->execute()->getFirst();


    if (!$ullwiki) {
      $docid = 1;
    } else {
      $docid = $ullwiki->getDocid() + 1;
    }
    
    return $docid;
  }
  
  /**
   * Add query where clauses for read access check 
   *
   * @param Doctrine_Query $q
   */
  public static function queryReadAccess(Doctrine_Query $q)
  {
    // Master Admin always has read access 
    if (UllUserTable::hasGroup('MasterAdmins'))
    {
      return $q;
    }
    
    $userId = sfContext::getInstance()->getUser()->getAttribute('user_id');
    
    $q->leftJoin('x.UllWikiAccessLevel.UllWikiAccessLevelAccess a');
    $q->leftJoin('a.UllGroup ag');
    
    // check public access
    $where = '
      a.UllPrivilege.slug = ?
        AND ag.display_name = ?  
    ';
    $values = array('read', 'Everyone');
    
    if ($userId)
    {
      // check access for any "logged in user"
      $where .= '
        OR a.UllPrivilege.slug = ?
          AND ag.display_name = ?  
      ';
      $values = array_merge($values, array('read', 'Logged in users'));      
      
      // check group membership
      $where .= '
        OR a.UllPrivilege.slug = ? 
          AND ag.UllUser.id = ?
      ';     
      $values = array_merge($values, array('read', $userId));
    }
    
//    var_dump($where);
//    var_dump($values);
    
    $q->addWhere($where, $values);

    return $q;
  }  
}
