<?php

/**
 * PluginUllCmsItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginUllCmsItem extends BaseUllCmsItem
{

  /**
   * String representation
   * 
   * @see lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord#__toString()
   */
  public function __toString()
  {
    return (string) $this->getFullPathName();
  }

  
  /**
   * Get the full path with parent names
   * 
   * @param $parent
   * @return string
   */
  public function getFullPathName($parent = null)
  {
    return implode(' - ', $this->buildFullPathName($parent));
  }    
  
  
  /**
   * Build the full path name
   * 
   * @param unknown_type $object
   * @return array
   */
  public function buildFullPathName($object = null)
  {
    if ($object === null)
    {
      $object = $this;
    }
    
    $return = array();
    
    if ($object->Parent->exists())
    {
      $return = array_merge($this->buildFullPathName($object->Parent), $return);
    }
    
    // We have to refetch the Translations for pages. Why?
    if (!$object->name)
    {
      $object->refreshRelated('Translation');
    }
    
    $return[] = $object->name;
    
    return $return;
  }
  
  
  /**
   * Get the sub items for current item
   *
   * @param boolean $hydration
   * @return mixed
   */
  public function getSubs($hydrationMode = null)
  {
    $q = new ullQuery('UllCmsItem');
    $q
      ->addSelect(array('slug', 'name'))
      ->addWhere('parent_ull_cms_item_id = ?', $this->id)
      ->addOrderby('name')
    ;
  
    $result = $q->execute(null, $hydrationMode);
  
    return $result;
  }    
  
  
}