<?php

/**
 * PluginUllNavigationItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginUllNavigationItem extends BaseUllNavigationItem
{
  
  public function __toString()
  {
    return (string) $this->getFullPathName();
  }

  public function getFullPathName($parent = null)
  {
    return implode(' - ', $this->buildFullPathName($parent));
  }    
  
  public function buildFullPathName($object = null)
  {
    if ($object === null)
    {
      $object = $this;
    }
    
    $return = array();
    
//    var_dump($object->slug);
//    var_dump($object->Parent->exists());
    
    if ($object->Parent->exists())
    {
      $return = array_merge($this->buildFullPathName($object->Parent), $return);
    }
    
    $return[] = $object->name;
    
    return $return;
  }
  

  
  /**
   * Get the sub items for current item
   *
   * @param boolean $hydration
   * @return mixed
   */
  public function getSubs($hydrationMode = null)
  {
    $q = new ullQuery('UllNavigationItem');
    $q
      ->addSelect(array('slug', 'name'))
      ->addWhere('parent_ull_navigation_item_id = ?', $this->id)
      ->addOrderby('name')
    ;
  
    $result = $q->execute(null, $hydrationMode);
  
    return $result;
  }  

}