<?php

/**
 * PluginUllCmsContentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCmsContentTypeTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCmsContentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCmsContentType');
    }
    
    /**
     * Find page types
     * 
     */
    public static function findForPages()
    {
      $q = new UllQuery('UllCmsContentType');
      $q
        ->where('type = ?', 'page')
        ->orderBy('name')
      ;

      return $q->execute();
    }    

    
    /**
     * Check if we have only one page type (=default)
     * and if so return it. 
     */
    public static function findOneAndOnlyPageType()
    {
      $types = self::findForPages();
      
      if (count($types) == 1)
      {
        return $types->getFirst();
      }
    }
    
    /**
     * Check if we have only one page type (=default)
     * and if so return it. 
     */
    public static function countPageTypes()
    {
      $q = new UllQuery('UllCmsContentType');
      $q
        ->where('type = ?', 'page')
      ;

      return $q->count();
    }    
    
    /**
     * Find content block types
     * 
     */
    public static function findForContentBlocks()
    {
      $q = new UllQuery('UllCmsContentType');
      $q
        ->where('type = ?', 'content_block')
        ->orderBy('name')
      ;

      return $q->execute();
    }    
}