<?php

/**
 * PluginUllCmsContentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCmsContentTypeTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCmsContentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCmsContentType');
    }
    
    /**
     * Find content block types
     * 
     */
    public static function findForContentBlocks()
    {
      $q = new UllQuery('UllCmsContentType');
      $q
        ->where('type = ?', 'content_block')
        ->orderBy('name')
      ;

      return $q->execute();
    }    
}