<?php

/**
 * PluginUllCmsElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCmsElementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCmsElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCmsElement');
    }
}