#!/bin/bash
#
echo 'ullright publish development files -> production'

PROJECT=`cat ../config/ull_project_name.txt`
SSHDATA=`cat ../config/ull_ssh_user_host.txt`

rsync -avz --delete --stats --exclude-from=../config/rsync_exclude.txt /var/www/$PROJECT/ $SSHDATA:/var/www/$PROJECT/

ssh $SSHDATA "cd /var/www/$PROJECT;symfony clear-controllers;symfony clear-cache;symfony fix-perms;cd batch;./ullright_dump_production"
scp $SSHDATA:/var/www/$PROJECT/data/sql/$PROJECT.production.mysql.dump ../data/sql


