#!/bin/bash
#
echo 'Update, reload and testing'

svn update
php symfony cache:clear
php symfony doctrine:build-all-reload --application=frontend --no-confirmation -t;
php symfony cache:clear
php symfony test:all
