# default rules
homepage:
  url:   /
  param: { module: myModule, action: index }

# Here's an homepage example for a ullCms page   
#homepage:
#  url:   /
#  param: { module: ullCms, action: show, slug: homepage }
#  class: sfDoctrineRoute
#  options: { model: UllCmsPage, type: object }  

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
