<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllProjectReporting extends UllRecord
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('ull_project_reporting');
        $this->hasColumn('ull_user_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('date', 'date', null, array('type' => 'date', 'notnull' => true));
        $this->hasColumn('ull_project_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('duration_seconds', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('comment', 'string', 4000, array('type' => 'string', 'length' => '4000'));
        $this->hasColumn('week', 'integer', null, array('type' => 'integer'));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('UllUser', array('local' => 'ull_user_id',
                                       'foreign' => 'id'));

        $this->hasOne('UllProject', array('local' => 'ull_project_id',
                                          'foreign' => 'id',
                                          'onDelete' => 'CASCADE'));
    }
}