<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllTimeReporting extends UllRecord
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('ull_time_reporting');
        $this->hasColumn('ull_user_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('date', 'date', null, array('type' => 'date', 'notnull' => true));
        $this->hasColumn('begin_work_at', 'time', null, array('type' => 'time'));
        $this->hasColumn('end_work_at', 'time', null, array('type' => 'time'));
        $this->hasColumn('begin_break1_at', 'time', null, array('type' => 'time'));
        $this->hasColumn('end_break1_at', 'time', null, array('type' => 'time'));
        $this->hasColumn('begin_break2_at', 'time', null, array('type' => 'time'));
        $this->hasColumn('end_break2_at', 'time', null, array('type' => 'time'));
        $this->hasColumn('begin_break3_at', 'time', null, array('type' => 'time'));
        $this->hasColumn('end_break3_at', 'time', null, array('type' => 'time'));
        $this->hasColumn('total_work_seconds', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('total_break_seconds', 'integer', null, array('type' => 'integer'));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('UllUser', array('local' => 'ull_user_id',
                                       'foreign' => 'id'));
    }
}