<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllTimePeriod extends UllRecord
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('ull_time_period');
        $this->hasColumn('name', 'string', 128, array('type' => 'string', 'notnull' => true, 'length' => '128'));
        $this->hasColumn('from_date', 'date', null, array('type' => 'date', 'notnull' => true));
        $this->hasColumn('to_date', 'date', null, array('type' => 'date', 'notnull' => true));
    }

    public function setUp()
    {
        parent::setUp();
    $i18n0 = new Doctrine_Template_I18n(array('fields' => array(0 => 'name')));
        $sluggable0 = new Doctrine_Template_Sluggable(array('unique' => true, 'fields' => array(0 => 'name'), 'canUpdate' => true));
        $this->actAs($i18n0);
        $this->actAs($sluggable0);
    }
}