<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllGroupPermission extends UllRecord
{
  public function setTableDefinition()
  {
    parent::setTableDefinition();
    $this->setTableName('ull_group_permission');
    $this->hasColumn('ull_group_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
    $this->hasColumn('ull_permission_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
  }

  public function setUp()
  {
    parent::setUp();
    $this->hasOne('UllGroup', array('local' => 'ull_group_id',
                                    'foreign' => 'id'));

    $this->hasOne('UllPermission', array('local' => 'ull_permission_id',
                                         'foreign' => 'id'));
  }
}