<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllJobTitle extends UllRecord
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('ull_job_title');
        $this->hasColumn('name', 'string', 100, array('type' => 'string', 'notnull' => true, 'length' => '100'));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('UllParentEntity', array('local' => 'id',
                                                'foreign' => 'ull_job_title_id'));
    }
}