<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllUser extends UllEntity
{
  public function setUp()
  {
    parent::setUp();
    $this->hasMany('UllGroup', array('refClass' => 'UllEntityGroup',
                                     'local' => 'ull_entity_id',
                                     'foreign' => 'ull_group_id'));

    $this->hasMany('TestTable', array('local' => 'id',
                                      'foreign' => 'ull_user_id'));

    $this->hasMany('UllEntityGroup', array('local' => 'id',
                                           'foreign' => 'ull_entity_id'));
  }
}