<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllSelect extends UllRecord
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('ull_select');
        $this->hasColumn('label', 'string', 64, array('type' => 'string', 'length' => '64'));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('UllSelectChild as UllSelectChildren', array('local' => 'id',
                                                                    'foreign' => 'ull_select_id'));

        $i18n0 = new Doctrine_Template_I18n(array('fields' => array(0 => 'label')));
        $sluggable0 = new Doctrine_Template_Sluggable(array('unique' => true, 'fields' => array(0 => 'label'), 'canUpdate' => true));
        $this->actAs($i18n0);
        $this->actAs($sluggable0);
    }
}