<?php
// auto-generated by sfPropelCrud
// date: 2008/02/20 12:05:38
?>
<?php use_helper('Object') ?>

<?php echo form_tag('ullUser/update') ?>

<?php echo object_input_hidden_tag($ull_user, 'getId') ?>

<table>
<tbody>
<tr>
  <th>First name:</th>
  <td><?php echo object_input_tag($ull_user, 'getFirstName', array (
  'size' => 64,
)) ?></td>
</tr>
<tr>
  <th>Last name:</th>
  <td><?php echo object_input_tag($ull_user, 'getLastName', array (
  'size' => 64,
)) ?></td>
</tr>
<tr>
  <th>Email:</th>
  <td><?php echo object_input_tag($ull_user, 'getEmail', array (
  'size' => 64,
)) ?></td>
</tr>
<tr>
  <th>Username:</th>
  <td><?php echo object_input_tag($ull_user, 'getUsername', array (
  'size' => 32,
)) ?></td>
</tr>
<tr>
  <th>Password:</th>
  <td><?php echo object_input_tag($ull_user, 'getPassword', array (
  'size' => 40,
)) ?></td>
</tr>
<tr>
  <th>Location:</th>
  <td><?php echo object_input_tag($ull_user, 'getLocationId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>User type:</th>
  <td><?php echo object_input_tag($ull_user, 'getUserType', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Creator user:</th>
  <td><?php echo object_input_tag($ull_user, 'getCreatorUserId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updator user:</th>
  <td><?php echo object_input_tag($ull_user, 'getUpdatorUserId', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($ull_user->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'ullUser/delete?id='.$ull_user->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'ullUser/show?id='.$ull_user->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'ullUser/list') ?>
<?php endif; ?>
</form>
