<?php
// auto-generated by sfPropelCrud
// date: 2008/02/20 12:05:38
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $ull_user->getId() ?></td>
</tr>
<tr>
<th>First name: </th>
<td><?php echo $ull_user->getFirstName() ?></td>
</tr>
<tr>
<th>Last name: </th>
<td><?php echo $ull_user->getLastName() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $ull_user->getEmail() ?></td>
</tr>
<tr>
<th>Username: </th>
<td><?php echo $ull_user->getUsername() ?></td>
</tr>
<tr>
<th>Password: </th>
<td><?php echo $ull_user->getPassword() ?></td>
</tr>
<tr>
<th>Location: </th>
<td><?php echo $ull_user->getLocationId() ?></td>
</tr>
<tr>
<th>User type: </th>
<td><?php echo $ull_user->getUserType() ?></td>
</tr>
<tr>
<th>Creator user: </th>
<td><?php echo $ull_user->getCreatorUserId() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $ull_user->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updator user: </th>
<td><?php echo $ull_user->getUpdatorUserId() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $ull_user->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'ullUser/edit?id='.$ull_user->getId()) ?>
&nbsp;<?php echo link_to('list', 'ullUser/list') ?>
