<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllVentoryItem extends UllRecord
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('ull_ventory_item');
        $this->hasColumn('serial_number', 'string', 128, array('type' => 'string', 'length' => '128'));
        $this->hasColumn('comment', 'string', 4000, array('type' => 'string', 'length' => '4000'));
        $this->hasColumn('ull_ventory_item_model_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('ull_user_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('ull_location_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('UllVentoryItemModel', array('local' => 'ull_ventory_item_model_id',
                                                   'foreign' => 'id'));

        $this->hasOne('UllUser', array('local' => 'ull_user_id',
                                       'foreign' => 'id'));

        $this->hasOne('UllLocation', array('local' => 'ull_location_id',
                                           'foreign' => 'id'));

        $this->hasMany('UllVentoryItemAttributeValue', array('local' => 'id',
                                                             'foreign' => 'ull_ventory_item_id'));
    }
}