<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllVentoryItemAttributeValue extends UllRecord
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('ull_ventory_item_attribute_value');
        $this->hasColumn('ull_ventory_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ull_ventory_item_type_attribute_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('comment', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('UllVentoryItem', array(
             'local' => 'ull_ventory_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('UllVentoryItemTypeAttribute', array(
             'local' => 'ull_ventory_item_type_attribute_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}