<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllVentoryTaking extends UllRecord
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('ull_ventory_taking');
        $this->hasColumn('name', 'string', 128, array('type' => 'string', 'length' => '128'));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('UllVentoryItemTaking', array('local' => 'id',
                                                     'foreign' => 'ull_ventory_taking_id'));
    }
}