<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllFlowColumnConfig extends UllRecord
{
  public function setTableDefinition()
  {
    parent::setTableDefinition();
    $this->setTableName('ull_flow_column_config');
    $this->hasColumn('ull_flow_app_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
    $this->hasColumn('slug', 'string', 32, array('type' => 'string', 'notnull' => true, 'length' => '32'));
    $this->hasColumn('label', 'string', 64, array('type' => 'string', 'length' => '64'));
    $this->hasColumn('sequence', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('ull_column_type_id', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('options', 'clob', null, array('type' => 'clob'));
    $this->hasColumn('is_enabled', 'boolean', null, array('type' => 'boolean', 'default' => true));
    $this->hasColumn('is_in_list', 'boolean', null, array('type' => 'boolean', 'default' => true));
    $this->hasColumn('is_mandatory', 'boolean', null, array('type' => 'boolean', 'default' => false));
    $this->hasColumn('is_subject', 'boolean', null, array('type' => 'boolean', 'default' => false));
    $this->hasColumn('default_value', 'string', 255, array('type' => 'string', 'length' => '255'));
  }

  public function setUp()
  {
    parent::setUp();
    $this->hasOne('UllFlowApp', array('local' => 'ull_flow_app_id',
                                      'foreign' => 'id',
                                      'onDelete' => 'CASCADE'));

    $this->hasOne('UllColumnType', array('local' => 'ull_column_type_id',
                                         'foreign' => 'id',
                                         'onDelete' => 'CASCADE'));

    $this->hasMany('UllFlowValue as UllFlowValues', array('local' => 'id',
                                                          'foreign' => 'ull_flow_column_config_id'));

    $i18n0 = new Doctrine_Template_I18n(array('fields' => array(0 => 'label')));
    $this->actAs($i18n0);
  }
}