<?php

/**
 * PluginUllContentElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllContentElementTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllContentElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllContentElement');
    }
}