<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllEmploymentType extends BaseUllEmploymentType
{

  /**
   * toString
   */
  public function __toString()
  {
    return (string) $this->name;
  }
}