<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllUser extends BaseUllUser
{
  
  /**
   * Record hook to generate the display_name
   *
   * @param unknown_type $event
   */
  public function preInsert($event)
  {
    $this->preUpdate($event);    
  }
  
  /**
   * Record hook to generate the display_name
   *
   * @param unknown_type $event
   */
  public function preUpdate($event)
  {
    $this->display_name = $this->first_name . ' ' . $this->last_name;
  }   
  
  /**
   * get User's Shortname
   *
   * @return string
   */
  public function getShortName() {

    $return = '';

    $first_name = substr($this->getFirstName(), 0, 1);

    if ($first_name) {
      $return .= $first_name . '.';
    }

    $last_name = substr($this->getLastName(), 0, 7);
    if (strlen($this->getLastName()) > 7) {
       $last_name .= '.';
    }

    $return .= $last_name;

    return $return;
  }
  
  /**
   * Get Full Name but the Lastname first
   * 
   * Example: Lennon John
   *
   * @return string
   */
  public function getLastNameFirst()
  {
    return $this->last_name . ' ' . $this->first_name;
  }   
}