<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUserTable extends EntityTable
{

  /**
   * check if a user is member of a group
   *
   * @param mixed $group      group_id or group name
   * @param integer $user_id  
   * @return boolean
   */
  public static function hasGroup($group, $user_id = null) 
  {
           
    // use session user_id as default entity
    if ($user_id === null) {
      $user_id = sfContext::getInstance()->getUser()->getAttribute('user_id'); 
    }
    
    $q = new Doctrine_Query;
    $q->from('User u, u.Group g')
      ->where('u.id = ?', $user_id)
    ;
    
    if (is_integer($group))
    {
      $q->addWhere('g.id = ?', $group);
    }
    else
    {
      $q->addWhere('g.name = ?', $group);
    }
      
    if ($q->count())
    {
      return true;
    }
  }
  
  
}