<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllUserTable extends UllEntityTable
{

  /**
   * check if a user is member of a group
   *
   * @param mixed $group      group_id, group name or array of group ids/names (not mixed!)
   * @param integer $user_id  
   * @return boolean
   */
  public static function hasGroup($group, $user_id = null) 
  {

    // use session user_id as default entity
    if ($user_id === null) {
      $user_id = sfContext::getInstance()->getUser()->getAttribute('user_id');
    }

    $q = new Doctrine_Query;
    $q->from('UllUser u, u.UllGroup g')
      ->where('u.id = ?', $user_id)
    ;

    if (!is_array($group))
    {
      $group = array($group);
    }

    if (is_integer($group[0]))
    {
      $group = implode(',', $group);
      $q->addWhere("g.id IN ($group)");
    }
    else
    {
      $group = '"' . implode('","', $group) . '"';
      $q->addWhere("g.name IN ($group)");
    }

    if ($q->count())
    {
      return true;
    }
  }

}