<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCloneUserTable extends UllEntityTable
{
  
  /**
   * Return choices for UllMetaWidgetEntity
   * 
   * @return array
   */
  public static function findChoices()
  {
    $clones = Doctrine::getTable('UllCloneUser')->findAll();
    $result = array();
    foreach($clones as $clone)
    {
      $result[$clone->id]['name'] = $clone->last_name_first;
      $result[$clone->id]['attributes']['class'] = 'color_clone_user_bg_ull_entity_widget';  
    }
    
    return $result;
  }  
  
}