<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllLocation extends BaseUllLocation
{
  public function __toString()
  {
    return $this->name;
  }

}