<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllTableConfigTable extends UllRecordTable
{
  protected static $cache = array();
  
  public static function findOneByDbTableNameCached($name)
  {
    if (!(isset(self::$cache[$name])))
    {
      self::$cache[$name] = Doctrine::getTable('UllTableConfig')->findOneByDbTableName($name);
    }
    
    return self::$cache[$name];
  }
  
  public static function clearCache()
  {
    self::$cache = array();
  }
}