<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllSelectChild extends BaseUllSelectChild
{

  /**
   * To string
   *
   * @return unknown
   */
  public function __toString()
  {
    return $this->label;
  }  
  
}