<?php

/**
 * PluginUllPaymentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllPaymentTypeTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllPaymentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllPaymentType');
    }
}