<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllSelect extends BaseUllSelect
{
  
  /**
   * To string
   *
   * @return unknown
   */
  public function __toString()
  {
    return $this->label;
  }

}