<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllPermission extends BaseUllPermission
{
  
  /**
   * return the permission's name
   *
   * @return string
   */
  public function __toString()
  {
    return $this->slug;
  }  

}