<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTestTableTable extends UllRecordTable
{
  
  protected function applyCustomColumnConfigSettings()
  {
    $this->columnsConfig['my_select_box']->setLabel('My custom select box label');
  }

}