<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllVentoryItemManufacturerTable extends UllRecordTable
{

  public static function findByTypeSlug($itemTypeSlug)
  {
    $q = new Doctrine_Query;
    $q
      ->from('UllVentoryItemManufacturer ma, ma.UllVentoryItemModel mo, mo.UllVentoryItemType t')
      ->where('t.slug = ?', $itemTypeSlug)
      ->orderBy('ma.name')
    ;
    return $q->execute();
  }
  
}