<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllVentoryItemTakingTable extends UllRecordTable
{
  
  public static function findByItemAndTaking($item, $taking)
  {
    $q = new Doctrine_Query;
    $q
      ->from('UllVentoryItemTaking x')
      ->where('x.ull_ventory_item_id = ?', $item->id)
      ->addWhere('x.ull_ventory_taking_id = ?', $taking->id)
    ;
    
    return $q->execute()->getFirst();
  }

}