<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllVentorySoftware extends BaseUllVentorySoftware
{
  
  public function __toString()
  {
    return (string) $this->name;
  }

}