<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllVentorySoftwareLicense extends BaseUllVentorySoftwareLicense
{

  public function __toString()
  {
    return (string) $this->license_key;
  }  
  
}