<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllVentoryItemAttributePresetTable extends UllRecordTable
{

  public static function findByModelIdAndTypeAttributeId($modelId, $typeAttributeId)
  {
    $q = new Doctrine_Query;
    $q
      ->from('UllVentoryItemAttributePreset x')
      ->where('x.ull_ventory_item_model_id = ?', $modelId)
      ->addWhere('x.ull_ventory_item_type_attribute_id = ?', $typeAttributeId)
    ;
    
    $result = $q->execute()->getFirst();
    return $result;      
  }   
  
  public static function findValueByModelIdAndTypeAttributeId($modelId, $typeAttributeId)
  {
    $preset = self::findByModelIdAndTypeAttributeId($modelId, $typeAttributeId);

    return ($preset) ? $preset->value : '';
  } 

  public static function saveValueByModelIdAndTypeAttributeId($value, $modelId, $typeAttributeId)
  {
    $preset = self::findByModelIdAndTypeAttributeId($modelId, $typeAttributeId);
    
    if (!$preset)
    {
      $preset = new UllVentoryItemAttributePreset;
      $preset->ull_ventory_item_model_id = $modelId;
      $preset->ull_ventory_item_type_attribute_id = $typeAttributeId;
    }
    
    $preset->value = $value;
    
    $preset->save();
  }
  
}