<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllVentoryItemTable extends UllRecordTable
{
  
  /**
   * Method to return new object for the create route
   * TODO: is there a better (=built in) way to do this?
   *  
   * @return UllVentoryItem
   */
  public static function getNew()
  {
    return new UllVentoryItem;    
  }

  
  /**
   * Applies model specific custom column configuration
   * 
   * @see plugins/ullCorePlugin/lib/model/doctrine/PluginUllRecordTable#applyCustomColumnConfigSettings()
   */
  protected function applyCustomColumnConfigSettings()
  {
    $c = &$this->columnConfigCollection;
    
    $c->disable(array('creator_user_id', 'created_at'));
    
    $c->create('ull_ventory_item_type_id')
      ->setMetaWidgetClassName('ullMetaWidgetForeignKey')
      ->setLabel('Type')
      ->setRelation(array(
        'model'             => 'UllVentoryItemType',
        'foreign_id'        => 'id'))
      ->setWidgetOptions(array('add_empty' => true))
      ->setValidatorOptions(array('required' => true))
      ->setAccess($this->getDefaultAccess())
    ;
    
    $c->create('ull_ventory_item_manufacturer_id')
      ->setMetaWidgetClassName('ullMetaWidgetForeignKey')
      ->setLabel(__('Manufacturer'))
      ->setRelation(array(
        'model'             => 'UllVentoryItemManufacturer',
        'foreign_id'        => 'id'))
      ->setWidgetOptions(array('add_empty' => true))
      ->setValidatorOptions(array('required' => true))
      ->setAllowCreate(true)
      ->setAccess($this->getDefaultAccess())
    ;    
        
    $c['ull_ventory_item_model_id']
      ->setLabel(__('Model'))
      ->setAllowCreate(true)
      ->setWidgetOption('add_empty', true)
    ;
    
    $c['serial_number']
      ->setLabel(__('Model'))
      ->setIsInList(false)
      ->setLabel(__('Serial number'))
    ;    
    
    $c['ull_entity_id']->setLabel(__('Owner', null, 'common'));

    $c['comment']->setLabel(__('Comment', null, 'common'));
    
    if ($c->isListAction())
    {
      $c->disable(array('id'));
      
      $c['inventory_number']
        ->setMetaWidgetClassName('ullMetaWidgetLink')
        ->setLabel(__('Inv.No.'))
      ;
      
      $c->create('ull_location_id')
        ->setMetaWidgetClassName('ullMetaWidgetForeignKey')
        ->setLabel(__('Location'))
        ->setRelation(array(
          'model'             => 'UllLocation',
          'foreign_id'        => 'id'))
        ->setAccess($this->getDefaultAccess())
      ;
      
      $c['updated_at']->setMetaWidgetClassName('ullMetaWidgetDate'); //?            
      
      $c->order(array(
        'inventory_number',
        'ull_ventory_item_type_id',
        'ull_ventory_item_manufacturer_id',
        'ull_ventory_item_model_id',
//        'serial_number',
        'ull_entity_id',
        'ull_location_id',      
        'comment'
      ));      
      
    }
    
    if ($c->isCreateOrEditAction())
    {
      $c['id']
        ->setAccess('w')
        ->setWidgetOption('is_hidden', true)
      ;
      $c['ull_entity_id']
        ->setWidgetOption('is_hidden', true)
        ->setOption('entity_classes', array('UllVentoryStatusDummyUser', 'UllUser'))
      ;
      $c['inventory_number']->setLabel(__('Inventory number'));
      
      $c->order(array(
        'ull_ventory_item_type_id',
        'ull_ventory_item_manufacturer_id',
        'ull_ventory_item_model_id',
        'inventory_number',
        'serial_number',
  //      'ull_entity_id',
  //      'ull_location_id',
        'comment'
      ));      
    }  
    
  }
  
}