<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllVentoryItemModel extends BaseUllVentoryItemModel
{
  
  /**
   * represents the object as a string
   *
   * @return string
   */
  public function __toString()
  {
    return $this->UllVentoryItemType . ' ' . $this->UllVentoryItemManufacturer . ' ' . $this->name;
  }

}