<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllVentoryStatusDummyUser extends BaseUllVentoryStatusDummyUser
{
  
  public function __toString()
  {
    $culture = sfDoctrineRecord::getDefaultCulture();
    $return = $this->Translation->$culture->display_name;
    //this executes a query each time, cache this?
    return $return;
  }
}