<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllVentorySoftwareTable extends UllRecordTable
{
  
  public static function findOrderedByName()
  {
    $q = new Doctrine_Query;
    $q
      ->from('UllVentorySoftware x')
      ->orderBy('x.name')
    ;
    
    return $q->execute();
  }

}