<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllVentoryItemAttribute extends BaseUllVentoryItemAttribute
{
  
  /**
   * represents the object as a string
   *
   * @return string
   */
  public function __toString()
  {
    return (string) $this->name;
  }  

}