<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllVentoryItem extends BaseUllVentoryItem
{
  
  public function findMemoriesOrderedByDate()
  {
    $q = new Doctrine_Query;
    $q
      ->from('UllVentoryItemMemory x')
      ->addWhere('x.ull_ventory_item_id = ?', $this->id)
      //additional ordering by id is a hack to properly order in case of exactly the same date 
      ->orderBy('x.transfer_at DESC, x.updated_at DESC, x.id DESC')  
    ;      
     
    return $q->execute();    
  }
  
  /**
   * Toggle inventory taking
   * 
   * Creates or removes an entry in UllVentoryItemTaking for the current (=latest)
   * UllVentoryTaking
   *  
   * @return none
   */
  public function toggleInventoryTaking()
  {
    $taking = UllVentoryTakingTable::findLatest();
    
    $itemTaking = UllVentoryItemTakingTable::findByItemAndTaking($this, $taking);
    
    if ($itemTaking)
    {
      $itemTaking->delete();
    }
    else
    {
      $this->UllVentoryItemTaking[]->UllVentoryTaking = UllVentoryTakingTable::findLatest();
      $this->UllVentoryItemTaking->save();
    }
    
  }

}