<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllVentoryOriginDummyUserTable extends UllVentoryStatusDummyUserTable
{

  /**
   * Return choices for UllMetaWidgetEntity
   * 
   * @return array
   */  
  public static function findChoices()
  {
    $q = new Doctrine_Query;
    $q
      ->select('u.id, t.display_name as name, t.lang')
      ->from('UllVentoryOriginDummyUser u INDEXBY u.id, u.Translation t')
      ->where('t.lang = ?', substr(sfContext::getInstance()->getUser()->getCulture(), 0, 2))
      ->orderBy('name')
    ;
    
    $result = $q->execute(null, Doctrine::HYDRATE_ARRAY);
    
    foreach($result as $key => $value)
    {
      unset($result[$key]['id']);
      unset($result[$key]['Translation']);
      $result[$key]['attributes']['class'] = 'color_light_bg_ull_ventory';  
    }
    
    return $result;
  }  
  
  
}