<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllVentoryTakingTable extends UllRecordTable
{
  
  /**
   * Return the current (=latest/newest) UllVentoryTaking
   * 
   * @return UllVentoryTaking
   */
  public static function findLatest()
  {
    $q = new Doctrine_Query;
    $q
      ->from('UllVentoryTaking x')
      ->orderBy('x.created_at DESC, x.id DESC')
      ->useResultCache(true)
    ;
    return $q->fetchOne();
  }

}