<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllVentoryItemType extends BaseUllVentoryItemType
{

  /**
   * represents the object as a string
   *
   * @return string
   */
  public function __toString()
  {
    return $this->name;
  }  
  
}