<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUllWikiAccessLevelAccess extends UllRecord
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('ull_wiki_access_level_access');
        $this->hasColumn('ull_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ull_privilege_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('model_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('UllGroup', array(
             'local' => 'ull_group_id',
             'foreign' => 'id'));

        $this->hasOne('UllPrivilege', array(
             'local' => 'ull_privilege_id',
             'foreign' => 'id'));

        $this->hasOne('UllWikiAccessLevel', array(
             'local' => 'model_id',
             'foreign' => 'id'));
    }
}