<?php

/**
 * PluginUllCourseStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCourseStatusTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCourseStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCourseStatus');
    }
}