<?php

/**
 * PluginUllCourseTariffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCourseTariffTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCourseTariffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCourseTariff');
    }
    
    /**
     * Find list of tariff ids for the given course
     * 
     * @param integer $courseId
     * @return array
     */
    public static function findIdsByCourseId($courseId)
    {
      $q = new Doctrine_Query();
      
      $q
        ->select('t.id')
        ->from('UllCourseTariff t, t.UllCourse c')
        ->where('c.id = ?', $courseId)
        ->orderBy('t.id')
      ;
      
      $results = $q->execute(null, Doctrine::HYDRATE_NONE);
      
      $return = array();
      
      foreach ($results as $result)
      {
        $return[] = $result[0];
      }
      
      return $return;
    }
}