<?php

/**
 * PluginUllCourseTariffBookingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCourseTariffBookingTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCourseTariffBookingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCourseTariffBooking');
    }
}