<?php

/**
 * PluginUllCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCourseTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCourse');
    }
}