<?php

/**
 * PluginUllCourseTariffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCourseTariffTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCourseTariffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCourseTariff');
    }
    
    
    public static function findIdsByCourseId($courseId)
    {
      $q = new Doctrine_Query();
      
      $q
        ->select('t.id')
        ->from('UllCourseTariff t, t.UllCourse c')
        ->where('c.id = ?', $courseId)
        ->orderBy('t.id')
      ;
      
      $result = $q->execute(null, Doctrine::HYDRATE_SINGLE_SCALAR);
      
      return $result;
    }
}