<?php

/**
 * PluginUllCourseBooking
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginUllCourseBooking extends BaseUllCourseBooking
{
  
  /**
   * Pre insert hook
   * 
   * @param unknown_type $event
   */
  public function preInsert($event)
  {
  }
  
  /**
   * pre save hook
   */
  public function preSave($event)
  {
    // Fixes fixture loading. At the moment of loading UllCourseBookings
    // UllCourseTariffCourse is not loaded yet.
    if (Doctrine::getTable('UllCourseTariffCourse')->count())
    {
      UllCourseBookingTable::validateTarif($this);
    }
    
    $this->updatePaidAt();
    
    $this->updatePricePaid();
    
    $this->defaultPriceNegotiated();
    
    $this->updateStatus();
  }

  /**
   * post save hook
   * 
   * @param unknown_type $event
   */
  public function postSave($event)
  {
    $this->updateSupernumerary();
    
    $this->UllCourse->updateProxies();    
  }
  
  /**
   * Send booking confirmation and payment information 
   */
  public function sendConfirmationMail()
  {
    // We cannot send emails without an email address
    if (!$this->UllUser->email)
    {
      return;
    }
    
    $mail = new ullsfMail('ull_course_booked');
    
    $mail->setFrom(
      sfConfig::get('app_ull_course_from_address'),
      sfConfig::get('app_ull_course_from_name')
    );
    $mail->addAddress($this->UllUser);

    $mail->usePartial('ullCourse/bookedMail', array(
      'booking' => $this
    ));
    
    $mail->send();
  }  
  
  /**
   * Send mail to confirm the payment
   */
  public function sendPaymentReceivedMail()
  {
    // We cannot send emails without an email address
    if (!$this->UllUser->email)
    {
      return;
    }
    
    $mail = new ullsfMail('ull_course_payment_received');
    
    $mail->setFrom(
      sfConfig::get('app_ull_course_from_address'),
      sfConfig::get('app_ull_course_from_name')
    );
    $mail->addAddress($this->UllUser);

    $mail->usePartial('ullCourse/paymentReceivedMail', array(
      'booking' => $this
    ));
    
    $mail->send();
  }  
  
  /**
   * Default the negotiated price to the tariff's price
   */
  public function defaultPriceNegotiated()
  {
    if (!$this->price_negotiated)
    {
      $this->price_negotiated = $this->UllCourseTariff->price;
    }
  }
  
  /**
   * Set the paid_at date when is_paid was modified
   */
  public function updatePaidAt()
  {
    $modified = $this->getModified();
    
    if (!array_key_exists('is_paid', $modified))
    {
      return;
    }
    
    if (true === $modified['is_paid'])
    {
      $this->paid_at = date('Y-m-d H:i:s');
    }
    if (false === $modified['is_paid'])
    {
      $this->paid_at = null;
    }    
  }
  
  /**
   * Default the price_paid if not set manually
   */
  public function updatePricePaid()
  {
    // The form returns an empty price as string '0.00'
    $price_paid = floatval($this->price_paid);
    
    if ($this->is_paid && empty($price_paid))
    {
      $this->price_paid = $this->UllCourseTariff->price;
    }    
  }  
  
  /**
   * Update the human readable UllCourseBookingStatus depending on the booking data
   */
  public function updateStatus()
  {
    if (!$this->is_active)
    {
      $this->UllCourseBookingStatus = $this->findStatus('deleted');
      
      return;
    }
    
    if ($this->price_paid && $this->price_paid < $this->price_negotiated)
    {
      $this->UllCourseBookingStatus = $this->findStatus('underpaid');
      
      return;      
    }
    
    if ($this->is_supernumerary_paid)
    {
      $this->UllCourseBookingStatus = $this->findStatus('supernumerary-paid');
      
      return;      
    }
    
    if ($this->price_paid && $this->price_paid > $this->price_negotiated)
    {
      $this->UllCourseBookingStatus = $this->findStatus('overpaid');
      
      return;      
    }

    if ($this->is_supernumerary_booked)
    {
      $this->UllCourseBookingStatus = $this->findStatus('supernumerary-booked');
      
      return;      
    }

    if ($this->is_paid)
    {
      $this->UllCourseBookingStatus = $this->findStatus('paid');
      
      return;      
    }      
    
    // default
    $this->UllCourseBookingStatus = $this->findStatus('booked');
  }
  
  /**
   *  Mark supernumerary bookings 
   */
  public function updateSupernumerary()
  {
    // called with postSave(), Therefore the record also exists and nothing changed.
    // getLastModified() gets the modifications from before the last save
    $modified = $this->getLastModified();
    
    if (isset($modified['is_paid']) || isset($modified['is_active']))
    {
      UllCourseBookingTable::updateSupernumerary($this->UllCourse->id);
    }
  }  
  
  /**
   * Ask wether we should send a booking confirmation mail now.
   */
  public function shouldWeSendConfirmationMail()
  {
    // lets support bookings unsaved, as well as previously saved
    if ($this->getModified())
    {
      $modified = $this->getModified(true);
    }
    else
    {
      $modified = $this->getLastModified(true);
    }
    
    // Send booking confirmation email for a new booking which is not paid yet
    if (
      array_key_exists('created_at', $modified) && 
      null === $modified['created_at'] && 
      false === $this->is_paid &&
      $this->UllUser->email
    )
    {
      return true;
    }    
    
    return false;
  }
  
  /**
   * Ask wether we should send a payment reiceived confirmation mail now.
   */
  public function shouldWeSendPaymentReceivedMail()
  {
    // lets support bookings unsaved, as well as previously saved
    if ($this->getModified())
    {
      $modified = $this->getModified();
    }
    else
    {
      $modified = $this->getLastModified();
    }
    
    // Send booking confirmation email for a new booking which is not paid yet
    if (
      isset($modified['is_paid']) && 
      true === $modified['is_paid'] &&
      false === $this->is_supernumerary_paid &&
      $this->UllUser->email
    )
    {
      return true;
    }    
    
    return false;
  }  
  
  /**
   * Helper shortcut method to get an UllCourseStatus by slug
   * 
   * @param string $slug
   */
  protected function findStatus($slug)
  {
    return Doctrine::getTable('UllCourseBookingStatus')->findOneBySlug($slug);
  }  
}