<?php

/**
 * PluginUllCourseBookingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCourseBookingTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCourseBookingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCourseBooking');
    }
}