<?php

/**
 * PluginUllCourseTariffCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCourseTariffCourseTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCourseTariffCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCourseTariffCourse');
    }
}