<?php

/**
 * PluginUllCourseTariffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCourseTariffTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCourseTariffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCourseTariff');
    }
}