<?php

/**
 * PluginUllCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCourseTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCourse');
    }
    
    /**
     * Get the number of courses with the given tags (string)
     * 
     * @param string $tags    tags separated by blanks " "
     * @return number
     */
    public static function countWithTags($tags)
    {
      $q = new ullQuery('UllCourse');
      $q
        ->addSearch($tags, array('duplicate_tags_for_search'))
        ->addWhere('is_active = ?', true)
      ;
      
      return $q->count();
    }
}