<?php

/**
 * PluginUllCourseBookingStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllCourseBookingStatusTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllCourseBookingStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllCourseBookingStatus');
    }
}