<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllProjectReporting extends BaseUllProjectReporting
{
  
  /**
   * pre save hook
   * 
   * auto calculate week
   *
   * @param unknown_type $event
   */
  public function preSave($event)
  {
    $this->week = date('YW', strtotime($this->date)); 
  }

  
  /**
   * Get string representation for linked models
   * 
   * @return string
   */
  public function getComment()
  {
    if ($this->linked_id)
    {
      $model = Doctrine::getTable($this->linked_model)->findOneById($this->linked_id);
      
      $return = '<a href="' . url_for($model->getEditUri()) . '">' .
        $model . '</a>';
        
      return $return;
    }
    
    return $this->_get('comment');
  }

}