<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllProject extends BaseUllProject
{
  
  /**
   * return the app's label
   *
   * @return string
   */
  public function __toString()
  {
    return (string) $this->name;
  }

}