<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUllProjectReporting extends BaseUllProjectReporting
{
  
  /**
   * pre save hook
   * 
   * auto calculate week
   *
   * @param unknown_type $event
   */
  public function preSave($event)
  {
    $this->week = date('YW', strtotime($this->date)); 
  }
}