<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllTimePeriodTable extends UllRecordTable
{
  
  /**
   * Find a period slug by a given date
   * 
   * @param $date
   * @return string
   */
  public static function findSlugByDate($date)
  {
    $q = new Doctrine_Query;
    $q
      ->select('tp.slug')
      ->from('UllTimePeriod tp')
      ->where('tp.from_date <= ?', $date)
      ->addWhere('tp.to_date >= ?', $date)
    ;
    
    $result = $q->fetchOne(null, Doctrine::HYDRATE_NONE);
    
    return $result[0];
  }

  
  /**
   * Find the current and all past periods
   * @param $date
   * @return unknown_type
   */
  public static function findCurrentAndPast($date = null)
  {
    if (!$date)
    {
      $date = date('Y-m-d');
    }
    
    $q = new Doctrine_Query;
    $q
      ->from('UllTimePeriod tp')
      ->where('tp.from_date <= ?', $date)
      ->orderBy('tp.from_date DESC')
    ;
    
    return $q->execute();
  }
  
}
  