<?php

/**
 * This class wraps a seach form generated by an UllSearchGenerator.
 */
class ullSearchForm
{
  protected $generator;
  
  /**
   * Returns a new instance of the UllSearchForm.
   * Needs an ullSearchGenerator to work.
   * 
   * @param $generator An ullSearchGenerator
   * @return ullSearchForm The new instance
   */
  public function __construct(ullSearchGenerator $generator)
  {
    $this->generator = $generator;

    $this->generator->buildForm();
         
    $this->generator->getForm()->getValidatorSchema()->setOption('allow_extra_fields', true);
    $this->generator->getForm()->getValidatorSchema()->setOption('filter_extra_fields', false);
               
    $this->generator->getForm()->getWidgetSchema()->setNameFormat('fields[%s]');
  }

  /**
   * Returns the wrapped generator.
   * 
   * @return ullSearchGenerator The wrapped generator
   */
  public function getGenerator() {
    return $this->generator;
  }
}

