all:
# set default_culture to invalid 'xx_XX' to detect unset culture and 
# allow auto-detect browser HTTP accept-language by i18nFilter
  default_culture:     xx_XX
  source:              XLIFF
#  source:              Creole
#  debug:               off
#  cache:               on
#  untranslated_prefix: "[T]"
#  untranslated_suffix: "[/T]"
