<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddSexWidget extends Doctrine_Migration
{
	public function up()
	{
    //added to ullUserSchema.yml / UllParentEntity / columns:
    //sex:
    //type: enum
    //values: [null, m, f]
		$this->addColumn('ull_entity', 'sex', 'string', array('length' => 255));
    
    //add ullMetaWidgetSex to the list of available column types
    $ct = new UllColumnType();
    $ct->namespace = 'ullCore';
    $ct->class = 'ullMetaWidgetSex';
    $ct->label = 'Sex';
    $ct->save();
	 
    //added to UllColumnConfig
		//  ull_user_cc_sex:
		//    Translation:
		//      en:
		//        label:      Sex
		//      de:
		//        label:      Geschlecht
		//    db_table_name:  UllUser
		//    db_column_name: sex
		//    is_in_list:     false
		//    UllColumnType:  sex
		//    namespace:      ullCore
		
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'sex';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->UllColumnType = $ct;
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Sex';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Geschlecht';
    
    $cc->save();
	}

	public function down()
	{
    throw new Exception('Not implemented.');
	}
}