<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddAdditionalUserFields extends Doctrine_Migration
{
  public function up()
  {
    $this->addNewTables();

    $this->addColumnsToUllEntity();

    $this->addColumnConfigs();
  }

  private function addNewTables()
  {
    //UllJobTitle
    $this->createTable('ull_job_title',
    array('id' => array('type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true),
     'namespace' => array('type' => 'string', 'length' => 32), 
     'name' => array('type' => 'string', 'notnull' => true, 'length' => 100),
     'created_at' => array('type' => 'timestamp', 'length' => 25),
     'updated_at' => array('type' => 'timestamp', 'length' => 25),
     'creator_user_id' => array('type' => 'integer', 'length' => 2147483647),
     'updator_user_id' => array('type' => 'integer', 'length' => 2147483647)),
    array('indexes' => array(), 'primary' => array(0 => 'id')));

    //UllCompany
    $this->createTable('ull_company',
    array('id' => array('type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true),
      'namespace' => array('type' => 'string', 'length' => 32),
      'name' => array('type' => 'string', 'notnull' => true, 'length' => 100),
      'short_name' => array('type' => 'string', 'length' => 15),
      'created_at' => array('type' => 'timestamp', 'length' => 25), 
      'updated_at' => array('type' => 'timestamp', 'length' => 25),
      'creator_user_id' => array('type' => 'integer', 'length' => 2147483647), 
      'updator_user_id' => array('type' => 'integer', 'length' => 2147483647)), 
    array('indexes' => array(), 'primary' => array(0 => 'id')));

    //UllLocation
    $this->createTable('ull_location',
    array('id' => array('type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true),
     'namespace' => array('type' => 'string', 'length' => 32), 
     'name' => array('type' => 'string', 'notnull' => true, 'length' => 100),
      'short_name' => array('type' => 'string', 'length' => 15),
      'street' => array('type' => 'string', 'length' => 200), 
      'city' => array('type' => 'string', 'length' => 100), 
      'country' => array('type' => 'string', 'length' => 10),
      'post_code' => array('type' => 'string', 'length' => 10),
      'phone_base_no' => array('type' => 'string', 'length' => 20),
      'phone_default_extension' => array('type' => 'integer', 'length' => 2147483647),
      'fax_base_no' => array('type' => 'string', 'length' => 20),
      'fax_default_extension' => array('type' => 'integer', 'length' => 2147483647),
      'created_at' => array('type' => 'timestamp', 'length' => 25),
      'updated_at' => array('type' => 'timestamp', 'length' => 25),
      'creator_user_id' => array('type' => 'integer', 'length' => 2147483647),
      'updator_user_id' => array('type' => 'integer', 'length' => 2147483647)),
    array('indexes' => array(), 'primary' => array(0 => 'id')));

    //UllDepartment
    $this->createTable('ull_department',
    array('id' => array('type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true),
      'namespace' => array('type' => 'string', 'length' => 32),
      'name' => array('type' => 'string', 'notnull' => true, 'length' => 100), 
      'short_name' => array('type' => 'string', 'length' => 15),
      'created_at' => array('type' => 'timestamp', 'length' => 25), 'updated_at' => array('type' => 'timestamp', 'length' => 25), 'creator_user_id' => array('type' => 'integer', 'length' => 2147483647), 'updator_user_id' => array('type' => 'integer', 'length' => 2147483647)), array('indexes' => array(), 'primary' => array(0 => 'id')));

    //UllEmploymentType
    $this->createTable('ull_employment_type',
    array('id' => array('type' => 'integer', 'length' => 20,
     'autoincrement' => true, 'primary' => true), '
     namespace' => array('type' => 'string', 'length' => 32), 
     'created_at' => array('type' => 'timestamp', 'length' => 25), 'updated_at' => array('type' => 'timestamp', 'length' => 25), 'creator_user_id' => array('type' => 'integer', 'length' => 2147483647), 'updator_user_id' => array('type' => 'integer', 'length' => 2147483647)), array('indexes' => array(), 'primary' => array(0 => 'id')));

    //UllEmploymentType translations
    $this->createTable('ull_employment_type_translation',
    array('id' => array('type' => 'integer', 'length' => 20, 'primary' => true),
      'name' => array('type' => 'string', 'notnull' => true, 'length' => 100),
      'lang' => array('fixed' => true, 'primary' => true, 'type' => 'string', 'length' => 2)),
    array('indexes' => array(), 'primary' => array(0 => 'id', 1 => 'lang')));

    //Add foreign keys
    $this->createForeignKey('ull_job_title', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_job_title_creator_user_id'));
    $this->createForeignKey('ull_job_title', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_job_title_updator_user_id'));
    $this->createForeignKey('ull_company', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_company_creator_user_id'));
    $this->createForeignKey('ull_company', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_company_updator_user_id'));
    $this->createForeignKey('ull_location', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_location_creator_user_id'));
    $this->createForeignKey('ull_location', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_location_updator_user_id'));
    $this->createForeignKey('ull_department', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_department_creator_user_id'));
    $this->createForeignKey('ull_department', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_department_updator_user_id'));
    $this->createForeignKey('ull_employment_type', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_employment_type_creator_user_id'));
    $this->createForeignKey('ull_employment_type', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_employment_type_updator_user_id'));
    $this->createForeignKey('ull_employment_type_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_employment_type', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_employment_type_translation_id'));
  }

  private function addColumnsToUllEntity()
  {
    $this->addColumn('ull_entity', 'entry_date', 'date', array('length' => 25));
    $this->addColumn('ull_entity', 'deactivation_date', 'date', array('length' => 25));
    $this->addColumn('ull_entity', 'separation_date', 'date', array('length' => 25));
    $this->addColumn('ull_entity', 'ull_employment_type_id', 'integer', array('length' => 2147483647));
    $this->addColumn('ull_entity', 'ull_job_title_id', 'integer', array('length' => 2147483647));
    $this->addColumn('ull_entity', 'ull_company_id', 'integer', array('length' => 2147483647));
    $this->addColumn('ull_entity', 'ull_department_id', 'integer', array('length' => 2147483647));
    $this->addColumn('ull_entity', 'ull_location_id', 'integer', array('length' => 2147483647));
    $this->addColumn('ull_entity', 'superior_ull_user_id', 'integer', array('length' => 2147483647));
    $this->addColumn('ull_entity', 'phone_extension', 'integer', array('length' => 20));
    $this->addColumn('ull_entity', 'is_show_extension_in_phonebook', 'boolean', array('length' => 25));
    $this->addColumn('ull_entity', 'fax_extension', 'integer', array('length' => 20));
    $this->addColumn('ull_entity', 'is_show_fax_extension_in_phonebook', 'boolean', array('length' => 25));
    $this->addColumn('ull_entity', 'comment', 'string', array('length' => 4000));
  }

  private function addColumnConfigs()
  {
    //  ull_user_cc_entrydate:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'entry_date';
    $cc->is_in_list = false;
    $cc->UllColumnType = Doctrine::getTable('UllColumnType')->findOneByLabel('Date');
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Entry date';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Eintrittsdatum';
    $cc->save();

    //  ull_user_cc_deactivationdate:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'deactivation_date';
    $cc->is_in_list = false;
    $cc->UllColumnType = Doctrine::getTable('UllColumnType')->findOneByLabel('Date');
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Deactivation date';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Deaktivierungsdatum';
    $cc->save();

    //  ull_user_cc_separationdate:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'separation_date';
    $cc->is_in_list = false;
    $cc->UllColumnType = Doctrine::getTable('UllColumnType')->findOneByLabel('Date');
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Separation date';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Austrittsdatum';
    $cc->save();

    //  ull_user_cc_et:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'ull_employment_type_id';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Employment type';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Beschäftigungsverhältnis';
    $cc->save();

    //  ull_user_cc_jt:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'ull_job_title_id';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Job title';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Funktion';
    $cc->save();

    //  ull_user_cc_company:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'ull_company_id';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Company';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Unternehmen';
    $cc->save();

    //  ull_user_cc_department:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'ull_department_id';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Department';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Abteilung';
    $cc->save();

    //  ull_user_cc_location:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'ull_location_id';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Location';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Standort';
    $cc->save();

    //  ull_user_cc_superior:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'superior_ull_user_id';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Superior';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Vorgesetzter';
    $cc->save();

    //  ull_user_cc_pext:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'phone_extension';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Phone extension';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Durchwahl';
    $cc->save();

    //  ull_user_cc_pextinpb:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'is_show_extension_in_phonebook';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Show phone ext. in phone book';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Durchwahl in Telefonb. anzeigen';
    $cc->save();

    //  ull_user_cc_fext:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'fax_extension';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Fax extension';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Fax-Durchwahl';
    $cc->save();

    //  ull_user_cc_fextinpb:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'is_show_fax_extension_in_phonebook';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Show fax ext. in phone book';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Fax-Durchwahl in Telefonb. anzeigen';
    $cc->save();

    //  ull_user_cc_comment:
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'comment';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Comment';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Kommentar';
    $cc->save();
  }

  public function down()
  {
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('entry_date')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('deactivation_date')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('separation_date')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_employment_type_id')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_job_title_id')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_company_id')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_department_id')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_location_id')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('superior_ull_user_id')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('phone_extension')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('is_show_extension_in_phonebook')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('fax_extension')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('is_show_fax_extension_in_phonebook')->delete();
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('comment')->delete();

    $this->dropTable('ull_job_title');
    $this->dropTable('ull_company');
    $this->dropTable('ull_location');
    $this->dropTable('ull_department');
    $this->dropTable('ull_employment_type_translation');
    $this->dropTable('ull_employment_type');

    $this->removeColumn('ull_entity', 'entry_date');
    $this->removeColumn('ull_entity', 'deactivation_date');
    $this->removeColumn('ull_entity', 'separation_date');
    $this->removeColumn('ull_entity', 'ull_employment_type_id');
    $this->removeColumn('ull_entity', 'ull_job_title_id');
    $this->removeColumn('ull_entity', 'ull_company_id');
    $this->removeColumn('ull_entity', 'ull_department_id');
    $this->removeColumn('ull_entity', 'ull_location_id');
    $this->removeColumn('ull_entity', 'superior_ull_user_id');
    $this->removeColumn('ull_entity', 'phone_extension');
    $this->removeColumn('ull_entity', 'is_show_extension_in_phonebook');
    $this->removeColumn('ull_entity', 'fax_extension');
    $this->removeColumn('ull_entity', 'is_show_fax_extension_in_phonebook');
    $this->removeColumn('ull_entity', 'comment');
  }
}