<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUserStatusField extends Doctrine_Migration
{
  public function up()
  {
    $this->createTable('ull_user_status',
    array('id' => array('type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true),
      'namespace' => array('type' => 'string', 'length' => 32), 
      'is_active' => array('type' => 'boolean', 'length' => 25),
      'created_at' => array('type' => 'timestamp', 'length' => 25), 
      'updated_at' => array('type' => 'timestamp', 'length' => 25), 
      'creator_user_id' => array('type' => 'integer', 'length' => 2147483647),
      'updator_user_id' => array('type' => 'integer', 'length' => 2147483647)),
    array('indexes' => array(), 'primary' => array(0 => 'id')));


    $this->createTable('ull_user_status_translation',
    array('id' => array('type' => 'integer', 'length' => 20, 'primary' => true),
        'name' => array('type' => 'string', 'notnull' => true, 'length' => 50), 
        'lang' => array('fixed' => true, 'primary' => true, 'type' => 'string', 'length' => 2)),
    array('indexes' => array(), 'primary' => array(0 => 'id', 1 => 'lang')));

    $this->createForeignKey('ull_user_status', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_user_status_creator_user_id'));
    $this->createForeignKey('ull_user_status', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_user_status_updator_user_id'));
    $this->createForeignKey('ull_user_status_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_user_status', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_user_status_translation_id'));
    
    $this->addColumn('ull_entity', 'ull_user_status_id', 'integer', array('length' => 2147483647));
    
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'ull_user_status_id';
    $cc->is_in_list = false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Status';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Status';
    $cc->save();
  }

  public function down()
  {
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_user_status_id')->delete();
    
    $this->dropTable('ull_user_status_translation');
    $this->dropTable('ull_user_status');
    
    $this->removeColumn('ull_entity', 'ull_user_status_id');
  }
}