<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddBaseWikiPermissions extends Doctrine_Migration
{
  public function up()
  {
    $group = new UllGroup();
    $group->display_name = 'WikiAdmins';
    $group->namespace = 'ullWiki';
    $group->save();
    
    $permissionEdit = new UllPermission();
    $permissionEdit->slug = 'ull_wiki_edit';
    $permissionEdit->namespace = 'ullWiki';
    $permissionEdit->save();

    $permissionDelete = new UllPermission();
    $permissionDelete->slug = 'ull_wiki_delete';
    $permissionDelete->namespace = 'ullWiki';
    $permissionDelete->save();
    
    $groupPermission = new UllGroupPermission();
    $groupPermission->UllGroup = $group;
    $groupPermission->UllPermission = $permissionEdit;
    $groupPermission->namespace = 'ullWiki';
    $groupPermission->save();
    
    $groupPermission = new UllGroupPermission();
    $groupPermission->UllGroup = $group;
    $groupPermission->UllPermission = $permissionDelete;
    $groupPermission->namespace = 'ullWiki';
    $groupPermission->save();    
  }


  public function down()
  {
    Doctrine::getTable('UllGroup')->findOneByDisplayName('WikiAdmins')->delete();
    Doctrine::getTable('UllPermission')->findOneBySlug('ull_wiki_edit')->delete();
    Doctrine::getTable('UllPermission')->findOneBySlug('ull_wiki_delete')->delete();
  }
}