<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddCountryWidget extends Doctrine_Migration
{
  public function up()
  {
    //add ullMetaWidgetCountry to the list of available column types
    $ct = new UllColumnType();
    $ct->namespace = 'ullCore';
    $ct->class = 'ullMetaWidgetCountry';
    $ct->label = 'Country';
    $ct->save();

    //make ullLocation country column use the new meta widget
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllLocation';
    $cc->db_column_name = 'country';
    $cc->is_in_list = true;
    $cc->namespace = 'ullCore';
    $cc->UllColumnType = $ct;
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Country';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Land';
    $cc->save();
  }

  public function down()
  {
    Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('country')->delete();
    Doctrine::getTable('UllColumnType')->findOneByClass('ullMetaWidgetCountry')->delete();
  }
}