<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddMassChangeSuperiorPerms extends Doctrine_Migration
{
  public function up()
  {
    $permissionMCS = new UllPermission();
    $permissionMCS->slug = 'ull_user_mass_change_superior';
    $permissionMCS->namespace = 'ullCore';
    $permissionMCS->save();
  }

  public function down()
  {
    Doctrine::getTable('UllPermission')->findOneBySlug('ull_user_mass_change_superior')->delete();
  }
}