<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdjustUserStatus extends Doctrine_Migration
{
	public function up()
	{
    $st = Doctrine::getTable('UllUserStatus')->findAll();
    foreach ($st as $us)
    {
      $us->slug = str_replace(' ', '_', strtolower($us->Translation['en']->name));
      $us->save();
    }
        
	  $as = Doctrine::getTable('UllUserStatus')->findOneBySlug('active');
    
	  $this->changeColumn('ull_entity', 'ull_user_status_id', 'integer',
        array('length' => 2147483647, 'default' => $as->id, 'notnull' => true));
        
	  $et = Doctrine::getTable('UllEntity')->findAll();
    foreach ($et as $ent)
    {
      $ent->ull_user_status_id = $as->id;
      $ent->save();
    }
	}

	public function down()
	{ 
	  $this->changeColumn('ull_entity', 'ull_user_status_id', 'integer',
        array('length' => 2147483647, 'default' => NULL, 'notnull' => false));
	}
}