<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddAddEmptyOptions extends Doctrine_Migration
{
  public function up()
  {
    $cc = Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_employment_type_id');
    $cc->options = $cc->options . ' add_empty=true';
    $cc->save();

    $cc = Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_job_title_id');
    $cc->options = $cc->options . ' add_empty=true';
    $cc->save();

    $cc = Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_company_id');
    $cc->options = $cc->options . ' add_empty=true';
    $cc->save();

    $cc = Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_department_id');
    $cc->options = $cc->options . ' add_empty=true';
    $cc->save();

    $cc = Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_location_id');
    $cc->options = $cc->options . ' add_empty=true';
    $cc->save();
  }

  public function down()
  {
    $cc = Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_employment_type_id');
    $cc->options = str_replace('add_empty=true', '', $cc->options);
    $cc->save();

    $cc = Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_job_title_id');
    $cc->options = str_replace('add_empty=true', '', $cc->options);
    $cc->save();

    $cc = Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_company_id');
    $cc->options = str_replace('add_empty=true', '', $cc->options);
    $cc->save();

    $cc = Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_department_id');
    $cc->options = str_replace('add_empty=true', '', $cc->options);
    $cc->save();

    $cc = Doctrine::getTable('UllColumnConfig')->findOneByDbColumnName('ull_location_id');
    $cc->options = str_replace('add_empty=true', '', $cc->options);
    $cc->save();
  }
}