<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddCcUllGroup extends Doctrine_Migration
{
  public function up()
  {
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'sex';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'entry_date';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'deactivation_date';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'separation_date';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'ull_employment_type_id';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'ull_job_title_id';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'ull_company_id';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'ull_department_id';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'ull_location_id';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'superior_ull_user_id';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'phone_extension';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'is_show_extension_in_phonebook';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'fax_extension';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'is_show_fax_extension_in_phonebook';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'comment';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'ull_user_status_id';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();
  }

  public function down()
  {
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'sex')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'entry_date')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'deactivation_date')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'separation_date')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'ull_employment_type_id')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'ull_job_title_id')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'ull_company_id')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'ull_department_id')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'ull_location_id')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'superior_ull_user_id')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'phone_extension')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'is_show_extension_in_phonebook')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'fax_extension')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'is_show_fax_extension_in_phonebook')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'comment')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
    
    Doctrine::getTable('UllColumnConfig')->createQuery('c')
    ->delete()->where('c.db_column_name = ?', 'ull_user_status_id')
    ->andWhere('c.db_table_name = ?', 'UllGroup')->execute();
  }
}