<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddInitialVersions extends Doctrine_Migration
{
  //this can be solved better by doing this in 13's postUp()
  //NOW we know ;)
  
  public function up()
  {
    $table = Doctrine::getTable('UllUser')->findAll();
    foreach ($table as $row)
    {
      $row->version = 1;
      $row->save();
    }

    $table = Doctrine::getTable('UllGroup')->findAll();
    foreach ($table as $row)
    {
      $row->version = 1;
      $row->save();
    }

    $table = Doctrine::getTable('UllPermission')->findAll();
    foreach ($table as $row)
    {
      $row->version = 1;
      $row->save();
    }

    $table = Doctrine::getTable('UllGroupPermission')->findAll();
    foreach ($table as $row)
    {
      $row->version = 1;
      $row->save();
    }
  }

  public function down()
  {
    echo("Migration 014's down() will be done by Migration 13's down()...\n");
  }
}