<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdjustUserSuperiorOptional extends Doctrine_Migration
{
  public function up()
  {
    $cc = Doctrine::getTable('UllColumnConfig')->createQuery('c')
            ->where('c.db_column_name = ?', 'superior_ull_user_id')
            ->andWhere('c.db_table_name = ?', 'UllUser')->fetchOne();
    
    $cc->options = $cc->options . ' add_empty=true';
    $cc->save();
  }

  public function down()
  {
    $cc = Doctrine::getTable('UllColumnConfig')->createQuery('c')
            ->where('c.db_column_name = ?', 'superior_ull_user_id')
            ->andWhere('c.db_table_name = ?', 'UllUser')->fetchOne();

    $cc->options = str_replace('add_empty=true', '', $cc->options);
    $cc->save();
  }
}