<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUllFlowAppIsPublicFlag extends Doctrine_Migration
{
  public function up()
  {
//    $this->addColumn('ull_flow_app', 'is_public', 'boolean', array('length' => 1));
    $this->addColumn('ull_flow_app', 'is_public', 'boolean');
  }

  public function down()
  {
    $this->removeColumn('ull_flow_app', 'is_public');
  }
}
