<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeleteVersionableTables extends Doctrine_Migration
{
  public function up()
  {
    $this->dropTable('ull_user_version');
    $this->dropTable('ull_group_version');
    $this->dropTable('ull_permission_version');
    $this->dropTable('ull_group_permission_version');
  }
  
  public function preUp()
  {
    echo "This migration will drop the *_version-tables\n";
    echo "If you have important past versions or scheduled updates,\n";
    echo "you should ctrl+c NOW! Waiting 5 seconds...\n";
    sleep(5);
    
    $table = Doctrine::getTable('UllUser')->findAll();
    foreach ($table as $row)
    {
      $row->version = 0;
      $row->save();
    }

    $table = Doctrine::getTable('UllGroup')->findAll();
    foreach ($table as $row)
    {
      $row->version = 0;
      $row->save();
    }

    $table = Doctrine::getTable('UllPermission')->findAll();
    foreach ($table as $row)
    {
      $row->version = 0;
      $row->save();
    }

    $table = Doctrine::getTable('UllGroupPermission')->findAll();
    foreach ($table as $row)
    {
      $row->version = 0;
      $row->save();
    }
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}