<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdjustVersionableToSuperVersionable extends Doctrine_Migration
{
  public function up()
  {
    $this->createTable('ull_user_version',
      array('id' => array('type' => 'integer', 'length' => 20, 'primary' => true),
      'namespace' => array('type' => 'string', 'length' => 32),
      'first_name' => array('type' => 'string', 'length' => 64),
      'last_name' => array('type' => 'string', 'length' => 64), 
      'display_name' => array('type' => 'string', 'length' => 64), 
      'username' => array('type' => 'string', 'length' => 64),
      'email' => array('type' => 'string', 'length' => 64), 
      'password' => array('type' => 'string', 'length' => 40),
      'sex' => array('type' => 'enum', 'values' =>  array( 0 => NULL,  1 => 'm',  2 => 'f', ), 'length' => NULL), 
      'entry_date' => array('type' => 'date', 'length' => 25),
      'deactivation_date' => array('type' => 'date', 'length' => 25), 
      'separation_date' => array('type' => 'date', 'length' => 25), 
      'ull_employment_type_id' => array('type' => 'integer', 'length' => 2147483647), 
      'ull_job_title_id' => array('type' => 'integer', 'length' => 2147483647), 
      'ull_company_id' => array('type' => 'integer', 'length' => 2147483647),
      'ull_department_id' => array('type' => 'integer', 'length' => 2147483647),
      'ull_location_id' => array('type' => 'integer', 'length' => 2147483647), 
      'superior_ull_user_id' => array('type' => 'integer', 'length' => 2147483647),
      'phone_extension' => array('type' => 'integer', 'length' => 20), 
      'is_show_extension_in_phonebook' => array('type' => 'boolean', 'length' => 25),
      'fax_extension' => array('type' => 'integer', 'length' => 20), 
      'is_show_fax_extension_in_phonebook' => array('type' => 'boolean', 'length' => 25),
      'comment' => array('type' => 'string', 'length' => 4000), 
      'ull_user_status_id' => array('type' => 'integer', 'notnull' => true, 'default' => '1', 'length' => 2147483647), 
      'type' => array('type' => 'string', 'length' => 255),
      'created_at' => array('type' => 'timestamp', 'length' => 25),
      'updated_at' => array('type' => 'timestamp', 'length' => 25), 
      'creator_user_id' => array('type' => 'integer', 'length' => 2147483647), 
      'updator_user_id' => array('type' => 'integer', 'length' => 2147483647), 
      'version' => array('primary' => true, 'type' => 'integer', 'length' => 8), 
      'reference_version' => array('type' => 'integer', 'length' => 8),
      'scheduled_update_date' => array('type' => 'date', 'length' => 2147483647),
      'done_at' => array('type' => 'timestamp', 'length' => 2147483647)),
      array('indexes' => array(), 'primary' => array(0 => 'id', 1 => 'version')));
  
    $this->createTable('ull_group_version',
      array('id' => array('type' => 'integer', 'length' => 20, 'primary' => true),
      'namespace' => array('type' => 'string', 'length' => 32),
      'first_name' => array('type' => 'string', 'length' => 64),
      'last_name' => array('type' => 'string', 'length' => 64),
      'display_name' => array('type' => 'string', 'length' => 64),
      'username' => array('type' => 'string', 'length' => 64), 
      'email' => array('type' => 'string', 'length' => 64),
      'password' => array('type' => 'string', 'length' => 40), 
      'sex' => array('type' => 'enum', 'values' =>  array( 0 => NULL,  1 => 'm',  2 => 'f', ), 'length' => NULL), 
      'entry_date' => array('type' => 'date', 'length' => 25),
      'deactivation_date' => array('type' => 'date', 'length' => 25),
      'separation_date' => array('type' => 'date', 'length' => 25),
      'ull_employment_type_id' => array('type' => 'integer', 'length' => 2147483647), 
      'ull_job_title_id' => array('type' => 'integer', 'length' => 2147483647),
      'ull_company_id' => array('type' => 'integer', 'length' => 2147483647), 
      'ull_department_id' => array('type' => 'integer', 'length' => 2147483647), 
      'ull_location_id' => array('type' => 'integer', 'length' => 2147483647), 
      'superior_ull_user_id' => array('type' => 'integer', 'length' => 2147483647),
      'phone_extension' => array('type' => 'integer', 'length' => 20),
      'is_show_extension_in_phonebook' => array('type' => 'boolean', 'length' => 25), 
      'fax_extension' => array('type' => 'integer', 'length' => 20),
      'is_show_fax_extension_in_phonebook' => array('type' => 'boolean', 'length' => 25), 
      'comment' => array('type' => 'string', 'length' => 4000), 
      'ull_user_status_id' => array('type' => 'integer', 'notnull' => true, 'default' => '1', 'length' => 2147483647),
      'type' => array('type' => 'string', 'length' => 255),
      'created_at' => array('type' => 'timestamp', 'length' => 25),
      'updated_at' => array('type' => 'timestamp', 'length' => 25), 
      'creator_user_id' => array('type' => 'integer', 'length' => 2147483647),
      'updator_user_id' => array('type' => 'integer', 'length' => 2147483647),
      'version' => array('primary' => true, 'type' => 'integer', 'length' => 8), 
      'reference_version' => array('type' => 'integer', 'length' => 8), 
      'scheduled_update_date' => array('type' => 'date', 'length' => 2147483647),
      'done_at' => array('type' => 'timestamp', 'length' => 2147483647)),
      array('indexes' => array(), 'primary' => array(0 => 'id', 1 => 'version')));
  
    $this->createTable('ull_permission_version',
      array('id' => array('type' => 'integer', 'length' => 20, 'primary' => true),
      'namespace' => array('type' => 'string', 'length' => 32),
      'slug' => array('type' => 'string', 'length' => 64),
      'created_at' => array('type' => 'timestamp', 'length' => 25),
      'updated_at' => array('type' => 'timestamp', 'length' => 25),
      'creator_user_id' => array('type' => 'integer', 'length' => 2147483647),
      'updator_user_id' => array('type' => 'integer', 'length' => 2147483647), 
      'version' => array('primary' => true, 'type' => 'integer', 'length' => 8), 
      'reference_version' => array('type' => 'integer', 'length' => 8), 
      'scheduled_update_date' => array('type' => 'date', 'length' => 2147483647), 
      'done_at' => array('type' => 'timestamp', 'length' => 2147483647)),
      array('indexes' => array(), 'primary' => array(0 => 'id', 1 => 'version')));
    
    $this->createTable('ull_group_permission_version', 
      array('id' => array('type' => 'integer', 'length' => 20, 'primary' => true),
      'namespace' => array('type' => 'string', 'length' => 32),
      'ull_group_id' => array('type' => 'integer', 'notnull' => true, 'length' => 2147483647),
      'ull_permission_id' => array('type' => 'integer', 'notnull' => true, 'length' => 2147483647),
      'created_at' => array('type' => 'timestamp', 'length' => 25),
      'updated_at' => array('type' => 'timestamp', 'length' => 25),
      'creator_user_id' => array('type' => 'integer', 'length' => 2147483647), 
      'updator_user_id' => array('type' => 'integer', 'length' => 2147483647), 
      'version' => array('primary' => true, 'type' => 'integer', 'length' => 8), 
      'reference_version' => array('type' => 'integer', 'length' => 8),
      'scheduled_update_date' => array('type' => 'date', 'length' => 2147483647), 
      'done_at' => array('type' => 'timestamp', 'length' => 2147483647)),
      array('indexes' => array(), 'primary' => array(0 => 'id', 1 => 'version')));


    $this->createForeignKey('ull_user_version',
      array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_entity',
        'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_user_version_id'));    
    $this->createForeignKey('ull_user_version',
      array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity',
        'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_user_version_updator_user_id'));    
    
    $this->createForeignKey('ull_group_version',
      array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_entity',
        'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_group_version_id'));
    $this->createForeignKey('ull_group_version',
      array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity',
        'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_group_version_updator_user_id'));
    
    $this->createForeignKey('ull_permission_version',
      array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_permission',
        'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_permission_version_id'));
    $this->createForeignKey('ull_permission_version',
      array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 
        'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_permission_version_updator_user_id'));
    
    $this->createForeignKey('ull_group_permission_version',
      array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_group_permission',
        'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_group_permission_version_id'));
    $this->createForeignKey('ull_group_permission_version', 
      array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity',
        'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_group_permission_version_updator_user_id'));
  }
  
  public function postUp()
  {
    $table = Doctrine::getTable('UllUser')->findAll();
    foreach ($table as $row)
    {
      $row->version = 1;
      $row->save();
    }

    $table = Doctrine::getTable('UllGroup')->findAll();
    foreach ($table as $row)
    {
      $row->version = 1;
      $row->save();
    }

    $table = Doctrine::getTable('UllPermission')->findAll();
    foreach ($table as $row)
    {
      $row->version = 1;
      $row->save();
    }

    $table = Doctrine::getTable('UllGroupPermission')->findAll();
    foreach ($table as $row)
    {
      $row->version = 1;
      $row->save();
    }
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
    
    //does this even make sense? :)
    //i think not...
    /*
    $this->removeColumn('ull_user_version', 'reference_version');
    $this->removeColumn('ull_user_version', 'scheduled_update_date');
    $this->removeColumn('ull_user_version', 'done_at');

    $this->removeColumn('ull_group_version', 'reference_version');
    $this->removeColumn('ull_group_version', 'scheduled_update_date');
    $this->removeColumn('ull_group_version', 'done_at');

    $this->removeColumn('ull_permission_version', 'reference_version');
    $this->removeColumn('ull_permission_version', 'scheduled_update_date');
    $this->removeColumn('ull_permission_version', 'done_at');

    $this->removeColumn('ull_group_permission_version', 'reference_version');
    $this->removeColumn('ull_group_permission_version', 'scheduled_update_date');
    $this->removeColumn('ull_group_permission_version', 'done_at');
    */
  }
}