<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddPercentageWidget extends Doctrine_Migration
{
  public function up()
  {
    //add ullMetaWidgetCountry to the list of available column types
    $ct = new UllColumnType();
    $ct->namespace = 'ullCore';
    $ct->class = 'ullMetaWidgetPercentage';
    $ct->label = 'Percentage';
    $ct->save();
    
  }

  public function down()
  {
    Doctrine::getTable('UllColumnType')->findOneByClass('ullMetaWidgetPercentage')->delete();
  }
}