<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUllPrivilege extends Doctrine_Migration
{
  public function up()
  {
    $this->createTable('ull_privilege', array('id' => array('type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true), 'namespace' => array('type' => 'string', 'length' => 32), 'slug' => array('type' => 'string', 'length' => 64), 'created_at' => array('type' => 'timestamp', 'length' => 25), 'updated_at' => array('type' => 'timestamp', 'length' => 25), 'creator_user_id' => array('type' => 'integer', 'length' => 2147483647), 'updator_user_id' => array('type' => 'integer', 'length' => 2147483647)), array('indexes' => array(), 'primary' => array(0 => 'id')));
    $this->createForeignKey('ull_privilege', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_privilege_creator_user_id'));
    $this->createForeignKey('ull_privilege', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_privilege_updator_user_id'));    
  }
  
  public function postUp()
  {
    $r = new UllPrivilege();
    $r->slug = 'read';
    $r->namespace = 'ullCore';
    $r->save();
    
    $r = new UllPrivilege();
    $r->slug = 'write';
    $r->namespace = 'ullCore';
    $r->save();    
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}