<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddVirtualGroupsData extends Doctrine_Migration
{
  public function up()
  {
    $r = new UllGroup();
    $r->display_name = 'Everyone';
    $r->is_virtual_group = true;
    $r->namespace = 'ullCore';
    $r->save();
    
    $r = new UllGroup();
    $r->display_name = 'Logged in users';
    $r->is_virtual_group = true;
    $r->namespace = 'ullCore';
    $r->save();
    
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllUser';
    $cc->db_column_name = 'is_virtual_group';
    $cc->is_enabled = false;
    $cc->namespace = 'ullCore';
    $cc->save();

    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllGroup';
    $cc->db_column_name = 'is_virtual_group';
    $cc->is_in_list= false;
    $cc->namespace = 'ullCore';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Is a virtual group';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Ist eine virtuelle Gruppe';    
    $cc->save();    
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}