<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUllWikiAccessLevel extends Doctrine_Migration
{
  public function up()
  {
    $this->createTable('ull_wiki_access_level', array('id' => array('type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true), 'namespace' => array('type' => 'string', 'length' => 32), 'slug' => array('type' => 'string', 'length' => 64), 'name' => array('type' => 'string', 'length' => 128), 'created_at' => array('type' => 'timestamp', 'length' => 25), 'updated_at' => array('type' => 'timestamp', 'length' => 25), 'creator_user_id' => array('type' => 'integer', 'length' => 2147483647), 'updator_user_id' => array('type' => 'integer', 'length' => 2147483647)), array('indexes' => array(), 'primary' => array(0 => 'id')));
    $this->createTable('ull_wiki_access_level_translation', array('id' => array('type' => 'integer', 'length' => 8, 'primary' => true), 'name' => array('type' => 'string', 'length' => 128), 'lang' => array('type' => 'string', 'length' => 2, 'fixed' => true, 'primary' => true)), array('indexes' => array(), 'primary' => array(0 => 'id', 1 => 'lang')));    
    $this->createTable('ull_wiki_access_level_access', array('id' => array('type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true), 'namespace' => array('type' => 'string', 'length' => 32), 'ull_group_id' => array('type' => 'integer', 'length' => 2147483647), 'ull_privilege_id' => array('type' => 'integer', 'length' => 2147483647), 'model_id' => array('type' => 'integer', 'length' => 2147483647), 'created_at' => array('type' => 'timestamp', 'length' => 25), 'updated_at' => array('type' => 'timestamp', 'length' => 25), 'creator_user_id' => array('type' => 'integer', 'length' => 2147483647), 'updator_user_id' => array('type' => 'integer', 'length' => 2147483647)), array('indexes' => array(), 'primary' => array(0 => 'id')));
    
    $this->addColumn('ull_wiki', 'ull_wiki_access_level_id', 'integer', array('length' => 2147483647));
        
    $this->createForeignKey('ull_wiki', array('local' => 'ull_wiki_access_level_id', 'foreign' => 'id', 'foreignTable' => 'ull_wiki_access_level', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_ull_wiki_access_level_id'));
    
    $this->createForeignKey('ull_wiki_access_level', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_creator_user_id'));
    $this->createForeignKey('ull_wiki_access_level', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_updator_user_id'));

    $this->createForeignKey('ull_wiki_access_level_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_wiki_access_level', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_translation_id'));

    $this->createForeignKey('ull_wiki_access_level_access', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_access_creator_user_id'));
    $this->createForeignKey('ull_wiki_access_level_access', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_access_updator_user_id'));
    $this->createForeignKey('ull_wiki_access_level_access', array('local' => 'ull_group_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_access_ull_group_id'));
    $this->createForeignKey('ull_wiki_access_level_access', array('local' => 'ull_privilege_id', 'foreign' => 'id', 'foreignTable' => 'ull_privilege', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_access_ull_privilege_id'));
    $this->createForeignKey('ull_wiki_access_level_access', array('local' => 'model_id', 'foreign' => 'id', 'foreignTable' => 'ull_wiki_access_level', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_access_model_id'));
  }
  
  public function postUp()
  {
    $r = new UllWikiAccessLevel();
    $r->Translation[0]->lang = 'en';
    $r->Translation[0]->label = 'Public readable';
    $r->Translation[1]->lang = 'de';
    $r->Translation[1]->label = 'Öffentlich lesbar';    
    $r->slug = 'public_readable';
    $r->namespace = 'ullWiki';
    $r->save();
    
    $r = new UllWikiAccessLevel();
    $r->Translation[0]->lang = 'en';
    $r->Translation[0]->label = 'Readable for logged in users';
    $r->Translation[1]->lang = 'de';
    $r->Translation[1]->label = 'Für angemeldete Besucher lesbar';    
    $r->slug = 'logged_in_readable';
    $r->namespace = 'ullWiki';
    $r->save();   
    
    $r = new UllWikiAccessLevelAccess();
    $r->UllGroup = Doctrine::getTable('UllGroup')->findOneByDisplayName('Everyone');
    $r->UllPrivilege = Doctrine::getTable('UllPrivilege')->findOneBySlug('read');
    $r->UllWikiAccessLevel = Doctrine::getTable('UllWikiAccessLevel')->findOneBySlug('public_readable');
    $r->namespace = 'ullWiki';
    $r->save();
    
    $r = new UllWikiAccessLevelAccess();
    $r->UllGroup = Doctrine::getTable('UllGroup')->findOneByDisplayName('WikiAdmins');
    $r->UllPrivilege = Doctrine::getTable('UllPrivilege')->findOneBySlug('write');
    $r->UllWikiAccessLevel = Doctrine::getTable('UllWikiAccessLevel')->findOneBySlug('public_readable');
    $r->namespace = 'ullWiki';
    $r->save();

    $r = new UllWikiAccessLevelAccess();
    $r->UllGroup = Doctrine::getTable('UllGroup')->findOneByDisplayName('Logged in users');
    $r->UllPrivilege = Doctrine::getTable('UllPrivilege')->findOneBySlug('read');
    $r->UllWikiAccessLevel = Doctrine::getTable('UllWikiAccessLevel')->findOneBySlug('logged_in_readable');
    $r->namespace = 'ullWiki';
    $r->save();    
    
    $r = new UllWikiAccessLevelAccess();
    $r->UllGroup = Doctrine::getTable('UllGroup')->findOneByDisplayName('WikiAdmins');
    $r->UllPrivilege = Doctrine::getTable('UllPrivilege')->findOneBySlug('write');
    $r->UllWikiAccessLevel = Doctrine::getTable('UllWikiAccessLevel')->findOneBySlug('logged_in_readable');
    $r->namespace = 'ullWiki';
    $r->save();      
    
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}