<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUllWikiAccessLevelColumn extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('ull_wiki', 'ull_wiki_access_level_id', 'integer', array('length' => 2147483647));
    $this->addColumn('ull_wiki_version', 'ull_wiki_access_level_id', 'integer', array('length' => 2147483647));
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}