<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddWikiAccessAdministration extends Doctrine_Migration
{
  public function up()
  {    
    $tc = new UllTableConfig();
    $tc->db_table_name = 'UllWikiAccessLevel';
    $tc->sort_columns = 'slug';
    $tc->search_columns = 'slug';
    $tc->namespace = 'ullWiki';
    $tc->Translation[0]->lang = 'en';
    $tc->Translation[0]->label = 'Manage list of access levels';
    $tc->Translation[1]->lang = 'de';
    $tc->Translation[1]->label = 'Verwalte Liste der Zugriffsrechte';
    $tc->save();      

    $tc = new UllTableConfig();
    $tc->db_table_name = 'UllWikiAccessLevelAccess';
    $tc->sort_columns = 'ull_group_id';
    $tc->search_columns = 'ull_group_id';
    $tc->namespace = 'ullWiki';
    $tc->Translation[0]->lang = 'en';
    $tc->Translation[0]->label = 'Manage list access rights';
    $tc->Translation[1]->lang = 'de';
    $tc->Translation[1]->label = 'Verwalte Zugriffsrechte';
    $tc->save();  
    
    
    $cc = new UllColumnConfig();
    $cc->db_table_name = 'UllWikiAccessLevelAccess';
    $cc->db_column_name = 'model_id';
    $cc->namespace = 'ullWiki';
    $cc->Translation[0]->lang = 'en';
    $cc->Translation[0]->label = 'Access level';
    $cc->Translation[1]->lang = 'de';
    $cc->Translation[1]->label = 'Zugriffsrecht';    
    $cc->save();     
    
  }
    
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}