<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddMissingUllWikiAccessLevelAccess extends Doctrine_Migration
{
  public function up()
  {
    $r = new UllWikiAccessLevelAccess();
    $r->UllGroup = Doctrine::getTable('UllGroup')->findOneByDisplayName('Logged in users');
    $r->UllPrivilege = Doctrine::getTable('UllPrivilege')->findOneBySlug('write');
    $r->UllWikiAccessLevel = Doctrine::getTable('UllWikiAccessLevel')->findOneBySlug('public_readable');
    $r->namespace = 'ullWiki';
    $r->save();
    
    $r = new UllWikiAccessLevelAccess();
    $r->UllGroup = Doctrine::getTable('UllGroup')->findOneByDisplayName('Logged in users');
    $r->UllPrivilege = Doctrine::getTable('UllPrivilege')->findOneBySlug('write');
    $r->UllWikiAccessLevel = Doctrine::getTable('UllWikiAccessLevel')->findOneBySlug('logged_in_readable');
    $r->namespace = 'ullWiki';
    $r->save();    
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}