<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUllVentoryEmploymentTypes extends Doctrine_Migration
{
  public function up()
  {    
    $object = new UllEmploymentType();
    $object->slug = 'status_dummy';
    $object->namespace = 'ullVentory';
    $object->Translation[0]->lang = 'en';
    $object->Translation[0]->name = 'Status dummy';
    $object->Translation[1]->lang = 'de';
    $object->Translation[1]->name = 'Status Dummy';
    $object->save();

    $object = new UllEmploymentType();
    $object->slug = 'origin_dummy';
    $object->namespace = 'ullVentory';
    $object->Translation[0]->lang = 'en';
    $object->Translation[0]->name = 'Origin dummy';
    $object->Translation[1]->lang = 'de';
    $object->Translation[1]->name = 'Herkunfts Dummy';
    $object->save();       
    
  }
    
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}