<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUllVentorySoftwareLicenseColumns extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('ull_ventory_software_license', 'supplier', 'string', array('length' => 128));
    $this->addColumn('ull_ventory_software_license', 'comment', 'string', array('length' => 4000));
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}