<?php
class RecreateForeignKeys extends Doctrine_Migration
{
  public function up()
  {
    //this retrieves all foreign keys belonging to the database
    //the currently active connection is using, and drops them
    
    $connection = Doctrine_Manager::connection();
    $info = Doctrine_Manager::getInstance()->parsePdoDsn($connection->getOption('dsn'));
    $dbName = $info['dbname'];
    
    $sql = 'SELECT table_name, constraint_name FROM information_schema.table_constraints ' .
      "WHERE constraint_type = 'FOREIGN KEY' and table_schema = '{$dbName}'";
    
    $constraints = $connection->fetchAll($sql);
    foreach ($constraints as $constraint)
    {
      $this->dropForeignKey($constraint['table_name'], $constraint['constraint_name']);
    }

    //recreate correct foreign keys
    $this->createForeignKey('ull_record', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_record_creator_user_id'));  
    $this->createForeignKey('ull_record', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_record_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_memory', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_memory_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item_memory', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_memory_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_memory', array('local' => 'ull_ventory_item_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_memory_ull_ventory_item_id')); 
    $this->createForeignKey('ull_ventory_item_memory', array('local' => 'source_ull_entity_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_memory_source_ull_entity_id'));  
    $this->createForeignKey('ull_ventory_item_memory', array('local' => 'target_ull_entity_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_memory_target_ull_entity_id'));  
    $this->createForeignKey('ull_ventory_item', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item', array('local' => 'ull_ventory_item_model_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item_model', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_ull_ventory_item_model_id')); 
    $this->createForeignKey('ull_ventory_item', array('local' => 'ull_entity_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_ull_entity_id')); 
    $this->createForeignKey('ull_ventory_item_model', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_model_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item_model', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_model_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_model', array('local' => 'ull_ventory_item_manufacturer_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item_manufacturer', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_model_ull_ventory_item_manufacturer_id'));  
    $this->createForeignKey('ull_ventory_item_model', array('local' => 'ull_ventory_item_type_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item_type', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_model_ull_ventory_item_type_id'));  
    $this->createForeignKey('ull_ventory_item_type_attribute', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_type_attribute_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item_type_attribute', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_type_attribute_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_type_attribute', array('local' => 'ull_ventory_item_type_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item_type', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_type_attribute_ull_ventory_item_type_id'));  
    $this->createForeignKey('ull_ventory_item_type_attribute', array('local' => 'ull_ventory_item_attribute_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item_attribute', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_type_attribute_item_attribute_id')); 
    $this->createForeignKey('ull_ventory_item_attribute', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_attribute_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item_attribute', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_attribute_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_attribute', array('local' => 'ull_column_type_id', 'foreign' => 'id', 'foreignTable' => 'ull_column_type', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_attribute_ull_column_type_id')); 
    $this->createForeignKey('ull_ventory_item_attribute_value', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_attribute_value_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item_attribute_value', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_attribute_value_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_attribute_value', array('local' => 'ull_ventory_item_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_attribute_value_ull_ventory_item_id')); 
    $this->createForeignKey('ull_ventory_item_attribute_value', array('local' => 'ull_ventory_item_type_attribute_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item_type_attribute', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_attribute_value_item_type_attribute_id'));  
    $this->createForeignKey('ull_ventory_taking', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_taking_creator_user_id'));  
    $this->createForeignKey('ull_ventory_taking', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_taking_updator_user_id'));  
    $this->createForeignKey('ull_ventory_software_license', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_software_license_creator_user_id'));  
    $this->createForeignKey('ull_ventory_software_license', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_software_license_updator_user_id'));  
    $this->createForeignKey('ull_ventory_software_license', array('local' => 'ull_ventory_software_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_software', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_software_license_ull_ventory_software_id')); 
    $this->createForeignKey('ull_ventory_item_type', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_type_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item_type', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_type_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_taking', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_taking_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item_taking', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_taking_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_taking', array('local' => 'ull_ventory_item_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_taking_ull_ventory_item_id')); 
    $this->createForeignKey('ull_ventory_item_taking', array('local' => 'ull_ventory_taking_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_taking', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_taking_ull_ventory_taking_id')); 
    $this->createForeignKey('ull_ventory_item_attribute_preset', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_attribute_preset_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item_attribute_preset', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_attribute_preset_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_attribute_preset', array('local' => 'ull_ventory_item_model_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item_model', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_attribute_preset_ull_ventory_item_model_id')); 
    $this->createForeignKey('ull_ventory_item_attribute_preset', array('local' => 'ull_ventory_item_type_attribute_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item_type_attribute', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_attribute_preset_item_type_attribute_id'));  
    $this->createForeignKey('ull_ventory_item_manufacturer', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_manufacturer_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item_manufacturer', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_manufacturer_updator_user_id'));  
    $this->createForeignKey('ull_ventory_software', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_software_creator_user_id'));  
    $this->createForeignKey('ull_ventory_software', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_software_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_software', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_software_creator_user_id'));  
    $this->createForeignKey('ull_ventory_item_software', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_item_software_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_software', array('local' => 'ull_ventory_item_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_software_ull_ventory_item_id')); 
    $this->createForeignKey('ull_ventory_item_software', array('local' => 'ull_ventory_software_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_software', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_software_ull_ventory_software_id')); 
    $this->createForeignKey('ull_ventory_item_software', array('local' => 'ull_ventory_software_license_id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_software_license', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_software_ull_ventory_software_license_id')); 
    $this->createForeignKey('ull_permission', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_permission_creator_user_id'));  
    $this->createForeignKey('ull_permission', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_permission_updator_user_id'));  
    $this->createForeignKey('ull_select_child', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_select_child_creator_user_id'));  
    $this->createForeignKey('ull_select_child', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_select_child_updator_user_id'));  
    $this->createForeignKey('ull_select_child', array('local' => 'ull_select_id', 'foreign' => 'id', 'foreignTable' => 'ull_select', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_select_child_ull_select_id'));  
    $this->createForeignKey('ull_job_title', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_job_title_creator_user_id'));  
    $this->createForeignKey('ull_job_title', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_job_title_updator_user_id'));  
    $this->createForeignKey('ull_company', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_company_creator_user_id'));  
    $this->createForeignKey('ull_company', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_company_updator_user_id'));  
    $this->createForeignKey('ull_location', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_location_creator_user_id'));  
    $this->createForeignKey('ull_location', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_location_updator_user_id'));  
    $this->createForeignKey('ull_privilege', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_privilege_creator_user_id'));  
    $this->createForeignKey('ull_privilege', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_privilege_updator_user_id'));  
    $this->createForeignKey('ull_column_type', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_column_type_creator_user_id'));  
    $this->createForeignKey('ull_column_type', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_column_type_updator_user_id'));  
    $this->createForeignKey('ull_column_config', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_column_config_creator_user_id'));  
    $this->createForeignKey('ull_column_config', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_column_config_updator_user_id'));  
    $this->createForeignKey('ull_column_config', array('local' => 'ull_column_type_id', 'foreign' => 'id', 'foreignTable' => 'ull_column_type', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_column_config_ull_column_type_id')); 
    $this->createForeignKey('ull_select', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_select_creator_user_id'));  
    $this->createForeignKey('ull_select', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_select_updator_user_id'));  
    $this->createForeignKey('ull_table_config', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_table_config_creator_user_id'));  
    $this->createForeignKey('ull_table_config', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_table_config_updator_user_id'));  
    $this->createForeignKey('ull_department', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_department_creator_user_id'));  
    $this->createForeignKey('ull_department', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_department_updator_user_id'));  
    $this->createForeignKey('ull_group_permission', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_group_permission_creator_user_id'));  
    $this->createForeignKey('ull_group_permission', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_group_permission_updator_user_id'));  
    $this->createForeignKey('ull_group_permission', array('local' => 'ull_group_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_group_permission_ull_group_id')); 
    $this->createForeignKey('ull_group_permission', array('local' => 'ull_permission_id', 'foreign' => 'id', 'foreignTable' => 'ull_permission', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_group_permission_ull_permission_id')); 
    $this->createForeignKey('ull_employment_type', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_employment_type_creator_user_id'));  
    $this->createForeignKey('ull_employment_type', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_employment_type_updator_user_id'));  
    $this->createForeignKey('ull_user_status', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_user_status_creator_user_id'));  
    $this->createForeignKey('ull_user_status', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_user_status_updator_user_id'));  
    $this->createForeignKey('ull_entity_group', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_entity_group_creator_user_id'));  
    $this->createForeignKey('ull_entity_group', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_entity_group_updator_user_id'));  
    $this->createForeignKey('ull_entity_group', array('local' => 'ull_entity_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_entity_group_ull_entity_id')); 
    $this->createForeignKey('ull_entity_group', array('local' => 'ull_group_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_entity_group_ull_group_id')); 
    $this->createForeignKey('ull_flow_step_action', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_step_action_creator_user_id'));  
    $this->createForeignKey('ull_flow_step_action', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_step_action_updator_user_id'));  
    $this->createForeignKey('ull_flow_step_action', array('local' => 'ull_flow_step_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_step', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_flow_step_action_ull_flow_step_id'));  
    $this->createForeignKey('ull_flow_step_action', array('local' => 'ull_flow_action_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_action', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_step_action_ull_flow_action_id')); 
    $this->createForeignKey('ull_flow_app_permission', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_app_permission_creator_user_id'));  
    $this->createForeignKey('ull_flow_app_permission', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_app_permission_updator_user_id'));  
    $this->createForeignKey('ull_flow_app_permission', array('local' => 'ull_flow_app_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_app', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_flow_app_permission_ull_flow_app_id')); 
    $this->createForeignKey('ull_flow_app_permission', array('local' => 'ull_permission_id', 'foreign' => 'id', 'foreignTable' => 'ull_permission', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_app_permission_ull_permission_id'));  
    $this->createForeignKey('ull_flow_value', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_value_creator_user_id'));  
    $this->createForeignKey('ull_flow_value', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_value_updator_user_id'));  
    $this->createForeignKey('ull_flow_value', array('local' => 'ull_flow_doc_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_doc', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_flow_value_ull_flow_doc_id')); 
    $this->createForeignKey('ull_flow_value', array('local' => 'ull_flow_column_config_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_column_config', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_flow_value_ull_flow_column_config_id')); 
    $this->createForeignKey('ull_flow_memory', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_memory_creator_user_id'));  
    $this->createForeignKey('ull_flow_memory', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_memory_updator_user_id'));  
    $this->createForeignKey('ull_flow_memory', array('local' => 'ull_flow_doc_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_doc', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_flow_memory_ull_flow_doc_id')); 
    $this->createForeignKey('ull_flow_memory', array('local' => 'ull_flow_step_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_step', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_memory_ull_flow_step_id')); 
    $this->createForeignKey('ull_flow_memory', array('local' => 'ull_flow_action_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_action', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_memory_ull_flow_action_id')); 
    $this->createForeignKey('ull_flow_memory', array('local' => 'assigned_to_ull_entity_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_memory_assigned_to_ull_entity_id'));  
    $this->createForeignKey('ull_flow_memory', array('local' => 'creator_ull_entity_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_memory_creator_ull_entity_id'));  
    $this->createForeignKey('ull_flow_column_config', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_column_config_creator_user_id'));  
    $this->createForeignKey('ull_flow_column_config', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_column_config_updator_user_id'));  
    $this->createForeignKey('ull_flow_column_config', array('local' => 'ull_flow_app_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_app', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_flow_column_config_ull_flow_app_id')); 
    $this->createForeignKey('ull_flow_column_config', array('local' => 'ull_column_type_id', 'foreign' => 'id', 'foreignTable' => 'ull_column_type', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_flow_column_config_ull_column_type_id'));  
    $this->createForeignKey('ull_flow_action', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_action_creator_user_id'));  
    $this->createForeignKey('ull_flow_action', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_action_updator_user_id'));  
    $this->createForeignKey('ull_flow_step', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_step_creator_user_id'));  
    $this->createForeignKey('ull_flow_step', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_step_updator_user_id'));  
    $this->createForeignKey('ull_flow_step', array('local' => 'ull_flow_app_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_app', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_flow_step_ull_flow_app_id')); 
    $this->createForeignKey('ull_flow_doc', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_doc_creator_user_id'));  
    $this->createForeignKey('ull_flow_doc', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_doc_updator_user_id'));  
    $this->createForeignKey('ull_flow_doc', array('local' => 'ull_flow_app_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_app', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_flow_doc_ull_flow_app_id')); 
    $this->createForeignKey('ull_flow_doc', array('local' => 'ull_flow_action_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_action', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_doc_ull_flow_action_id')); 
    $this->createForeignKey('ull_flow_doc', array('local' => 'assigned_to_ull_entity_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_doc_assigned_to_ull_entity_id'));  
    $this->createForeignKey('ull_flow_doc', array('local' => 'assigned_to_ull_flow_step_id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_step', 'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'ull_flow_doc_assigned_to_ull_flow_step_id'));  
    $this->createForeignKey('ull_flow_app', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_app_creator_user_id'));  
    $this->createForeignKey('ull_flow_app', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_flow_app_updator_user_id'));  
    $this->createForeignKey('ull_wiki_access_level_access', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_access_creator_user_id'));  
    $this->createForeignKey('ull_wiki_access_level_access', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_access_updator_user_id'));  
    $this->createForeignKey('ull_wiki_access_level_access', array('local' => 'ull_group_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_access_ull_group_id'));  
    $this->createForeignKey('ull_wiki_access_level_access', array('local' => 'ull_privilege_id', 'foreign' => 'id', 'foreignTable' => 'ull_privilege', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_access_ull_privilege_id')); 
    $this->createForeignKey('ull_wiki_access_level_access', array('local' => 'model_id', 'foreign' => 'id', 'foreignTable' => 'ull_wiki_access_level', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_access_model_id')); 
    $this->createForeignKey('ull_wiki', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_creator_user_id'));  
    $this->createForeignKey('ull_wiki', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_updator_user_id'));  
    $this->createForeignKey('ull_wiki', array('local' => 'ull_wiki_access_level_id', 'foreign' => 'id', 'foreignTable' => 'ull_wiki_access_level', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_ull_wiki_access_level_id')); 
    $this->createForeignKey('ull_wiki_access_level', array('local' => 'creator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_creator_user_id'));  
    $this->createForeignKey('ull_wiki_access_level', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_wiki_access_level_updator_user_id'));  
    $this->createForeignKey('ull_ventory_item_attribute_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item_attribute', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_attribute_translation_id'));
    // disabled, because we didn't migrate it to the customers because the table is not used  
//    $this->createForeignKey('ull_parent_entity_version', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_parent_entity', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_parent_entity_version_id')); 
//    $this->createForeignKey('ull_parent_entity_version', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_parent_entity_version_updator_user_id'));  
//    $this->createForeignKey('ull_entity_version', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_entity_version_id'));  
//    $this->createForeignKey('ull_entity_version', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_entity_version_updator_user_id'));  
    $this->createForeignKey('ull_ventory_status_dummy_user_version', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_status_dummy_user_version_id'));  
    $this->createForeignKey('ull_ventory_status_dummy_user_version', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_status_dummy_user_version_updator_user_id'));  
    $this->createForeignKey('ull_ventory_status_dummy_user_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_status_dummy_user_translation_id'));  
    $this->createForeignKey('ull_ventory_origin_dummy_user_version', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_origin_dummy_user_version_id'));  
    $this->createForeignKey('ull_ventory_origin_dummy_user_version', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_ventory_origin_dummy_user_version_updator_user_id'));  
    $this->createForeignKey('ull_ventory_origin_dummy_user_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_origin_dummy_user_translation_id'));  
    $this->createForeignKey('ull_ventory_item_type_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_ventory_item_type', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_ventory_item_type_translation_id')); 
    $this->createForeignKey('ull_permission_version', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_permission', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_permission_version_id'));  
    $this->createForeignKey('ull_permission_version', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_permission_version_updator_user_id'));  
    $this->createForeignKey('ull_select_child_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_select_child', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_select_child_translation_id'));  
    $this->createForeignKey('ull_column_config_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_column_config', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_column_config_translation_id')); 
    $this->createForeignKey('ull_select_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_select', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_select_translation_id'));  
    $this->createForeignKey('ull_table_config_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_table_config', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_table_config_translation_id'));  
    $this->createForeignKey('ull_group_permission_version', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_group_permission', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_group_permission_version_id'));  
    $this->createForeignKey('ull_group_permission_version', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_group_permission_version_updator_user_id'));  
    $this->createForeignKey('ull_group_version', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_group_version_id'));  
    $this->createForeignKey('ull_group_version', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_group_version_updator_user_id'));  
    $this->createForeignKey('ull_employment_type_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_employment_type', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_employment_type_translation_id')); 
    $this->createForeignKey('ull_user_version', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_user_version_id'));  
    $this->createForeignKey('ull_user_version', array('local' => 'updator_user_id', 'foreign' => 'id', 'foreignTable' => 'ull_entity', 'onUpdate' => NULL, 'onDelete' => NULL, 'name' => 'ull_user_version_updator_user_id'));  
    $this->createForeignKey('ull_user_status_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_user_status', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_user_status_translation_id')); 
    $this->createForeignKey('ull_flow_column_config_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_column_config', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_flow_column_config_translation_id'));  
    $this->createForeignKey('ull_flow_action_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_action', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_flow_action_translation_id')); 
    $this->createForeignKey('ull_flow_step_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_step', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_flow_step_translation_id')); 
    $this->createForeignKey('ull_flow_app_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_flow_app', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_flow_app_translation_id'));  
    $this->createForeignKey('ull_wiki_version', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_wiki', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_wiki_version_id'));  
    $this->createForeignKey('ull_wiki_access_level_translation', array('local' => 'id', 'foreign' => 'id', 'foreignTable' => 'ull_wiki_access_level', 'onUpdate' => 'CASCADE', 'onDelete' => 'CASCADE', 'name' => 'ull_wiki_access_level_translation_id')); 
  }
  
  public function down()
  {    
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}