<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddItemAttributeOptionsColumn extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('ull_ventory_item_attribute', 'options', 'string', array('length' => 4000));
	}

	public function down()
	{
    $this->removeColumn('ull_ventory_item_attribute', 'options');
	}
}