<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SluggifyUllSelect extends Doctrine_Migration
{
  public function up()
  {
    $this->changeColumn('ull_select', 'slug', 'string', array('length' => 255));
    $this->addColumn('ull_select_child', 'slug', 'string', array('length' => 255));    
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}