<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SluggifyUllFlow extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('ull_flow_column_config', 'is_priority', 'boolean');
    $this->addColumn('ull_flow_column_config', 'is_tagging', 'boolean');
    
    $this->changeColumn('ull_flow_app', 'slug', 'string', array('length' => 255));
    $this->changeColumn('ull_flow_column_config', 'slug', 'string', array('length' => 255));
    $this->changeColumn('ull_flow_action', 'slug', 'string', array('length' => 255));
    $this->changeColumn('ull_flow_step', 'slug', 'string', array('length' => 255));
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}