<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UllFlowDuplicateColumns extends Doctrine_Migration
{
  public function up()
  {
    $columnConfigs = Doctrine::getTable('UllFlowColumnConfig')->findBySlug('column_priority');
    foreach ($columnConfigs as $columnConfig)
    {
      $columnConfig->is_priority = true;
      $columnConfig->save();
    }
    
    $columnConfigs = Doctrine::getTable('UllFlowColumnConfig')->findBySlug('column_tags');
    foreach ($columnConfigs as $columnConfig)
    {
      $columnConfig->is_tagging = true;
      $columnConfig->save();
    }

    // unique-fy slugs
    $columnConfigs = Doctrine::getTable('UllFlowColumnConfig')->findAll();
    foreach ($columnConfigs as $columnConfig)
    {
      $columnConfig->save();
    }
    
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}