<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeleteOldTableConfig extends Doctrine_Migration
{
  public function up()
  {
    $libPath = sfConfig::get('sf_lib_dir');
    unlink($libPath . '/model/doctrine/ullCorePlugin/base/BaseUllTableConfig.class.php');
    unlink($libPath . '/model/doctrine/ullCorePlugin/UllTableConfig.class.php');
    unlink($libPath . '/model/doctrine/ullCorePlugin/UllTableConfigTable.class.php');
    unlink($libPath . '/form/doctrine/ullCorePlugin/base/BaseUllTableConfigForm.class.php');
    unlink($libPath . '/form/doctrine/ullCorePlugin/UllTableConfigForm.class.php');
    unlink($libPath . '/filter/doctrine/ullCorePlugin/base/BaseUllTableConfigFormFilter.class.php');
    unlink($libPath . '/filter/doctrine/ullCorePlugin/UllTableConfigFormFilter.class.php');
    unlink($libPath . '/form/doctrine/ullCorePlugin/base/BaseUllTableConfigTranslationForm.class.php');
    unlink($libPath . '/form/doctrine/ullCorePlugin/UllTableConfigTranslationForm.class.php');
    unlink($libPath . '/filter/doctrine/ullCorePlugin/base/BaseUllTableConfigTranslationFormFilter.class.php');
    unlink($libPath . '/filter/doctrine/ullCorePlugin/UllTableConfigTranslationFormFilter.class.php');
    
    $dbh = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
    $dbh->exec("DROP TABLE ull_table_config_translation");
    $dbh->exec("DROP TABLE ull_table_config");  
  }
  
  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException('This migration can not be undone.');
  }
}