<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addullcmsitem extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ull_cms_item', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'namespace' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'parent_ull_cms_item_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'length' => 25,
             ),
             'sequence' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'link' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'creator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'updator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'ull_cms_item_type' => 
              array(
              'fields' => 
              array(
               0 => 'type',
              ),
              ),
              'sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ull_cms_item');
    }
}