<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUllVoucherTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ull_voucher', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'namespace' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'text' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 400,
             ),
             'is_printed' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'is_redeemed' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'redeemed_at' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
             ),
             'redeemed_ull_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'creator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'updator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ull_voucher');
    }
}