<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUllVoucherfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ull_voucher', 'ull_voucher_creator_user_id_ull_entity_id', array(
             'name' => 'ull_voucher_creator_user_id_ull_entity_id',
             'local' => 'creator_user_id',
             'foreign' => 'id',
             'foreignTable' => 'ull_entity',
             ));
        $this->createForeignKey('ull_voucher', 'ull_voucher_updator_user_id_ull_entity_id', array(
             'name' => 'ull_voucher_updator_user_id_ull_entity_id',
             'local' => 'updator_user_id',
             'foreign' => 'id',
             'foreignTable' => 'ull_entity',
             ));
        $this->createForeignKey('ull_voucher', 'ull_voucher_redeemed_ull_user_id_ull_entity_id', array(
             'name' => 'ull_voucher_redeemed_ull_user_id_ull_entity_id',
             'local' => 'redeemed_ull_user_id',
             'foreign' => 'id',
             'foreignTable' => 'ull_entity',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ull_voucher', 'ull_voucher_creator_user_id_ull_entity_id');
        $this->dropForeignKey('ull_voucher', 'ull_voucher_updator_user_id_ull_entity_id');
        $this->dropForeignKey('ull_voucher', 'ull_voucher_redeemed_ull_user_id_ull_entity_id');
    }
}