<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addUllWikiIsOutdated extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('ull_wiki', 'is_outdated', 'boolean', 25, array('default' => 0));
        $this->addColumn('ull_wiki_version', 'is_outdated', 'boolean', 25, array('default' => 0));       
    }

    public function down()
    {
        $this->removeColumn('ull_wiki', 'is_outdated');
        $this->removeColumn('ull_wiki_version', 'is_outdated');
    }
}