<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addullcoursebooking extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ull_course_booking', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'namespace' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'ull_course_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'ull_course_tariff_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'ull_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'ull_course_booking_status_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'ull_payment_type_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'are_terms_of_use_accepted' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'is_paid' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'paid_at' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
             ),
             'price_paid' => 
             array(
              'type' => 'decimal',
              'length' => 15,
              'scale' => 2,
             ),
             'price_negotiated' => 
             array(
              'type' => 'decimal',
              'length' => 15,
              'scale' => 2,
              'notnull' => true,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'length' => 25,
             ),
             'is_supernumerary_booked' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'is_supernumerary_paid' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'comment' => 
             array(
              'type' => 'string',
              'length' => 4000,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'creator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'updator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'version' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ull_course_booking');
    }
}