<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addullcourse extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ull_course', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'namespace' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'trainer_ull_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'begin_date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'end_date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'begin_time' => 
             array(
              'type' => 'time',
              'length' => 25,
             ),
             'end_time' => 
             array(
              'type' => 'time',
              'length' => 25,
             ),
             'number_of_units' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'is_equipment_included' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'is_admission_included' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'length' => 25,
             ),
             'is_canceled' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'min_number_of_participants' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'max_number_of_participants' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'proxy_number_of_participants_applied' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'proxy_number_of_participants_paid' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'proxy_turnover' => 
             array(
              'type' => 'decimal',
              'length' => 15,
              'scale' => 2,
             ),
             'duplicate_tags_for_search' => 
             array(
              'type' => 'string',
              'length' => 4000,
             ),
             'ull_course_status_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'creator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'updator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'ull_course_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ull_course');
    }
}