<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addulluseronetimetoken extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ull_user_one_time_token', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'namespace' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'ull_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'token' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 16,
             ),
             'is_used_up' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'creator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'updator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }
    
    public function postUp()
    {
        RecreateForeignKeysTask::createAllForeignKeysFromModel();
    }     

    public function down()
    {
        $this->dropTable('ull_user_one_time_token');
    }
}