<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addullmailerrortranslation extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ull_mail_error_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'lang' => 
             array(
              'fixed' => true,
              'primary' => true,
              'type' => 'string',
              'length' => 2,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
    }
    
  public function postUp()
  {
      RecreateForeignKeysTask::createAllForeignKeysFromModel();
  }     

    public function down()
    {
        $this->dropTable('ull_mail_error_translation');
    }
}