<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addbigwish extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('bigwish', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'namespace' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'uuid' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 128,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 256,
             ),
             'comment' => 
             array(
              'type' => 'string',
              'length' => 2000,
             ),
             'ull_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'price' => 
             array(
              'type' => 'decimal',
              'length' => 15,
              'scale' => 2,
              'notnull' => true,
             ),
             'num_puzzle_cols' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'num_puzzle_rows' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'source_width_px' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'source_height_px' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'piece_width_px' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'piece_height_px' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'total_width_px' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'total_height_px' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'creator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'updator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('bigwish');
    }
}