<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addbigwishfulfilment extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('bigwish_fulfilment', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'namespace' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'uuid' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 128,
             ),
             'comment' => 
             array(
              'type' => 'string',
              'length' => 2000,
             ),
             'num_pieces' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'ull_user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'bigwish_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'creator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'updator_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

public function postUp()
{
    RecreateForeignKeysTask::createAllForeignKeysFromModel();
} 


    public function down()
    {
        $this->dropTable('bigwish_fulfilment');
    }
}
