<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2008/04/01 08:36:49
sfConfig::add(array(
  'sf_i18n_default_culture' => 'xx_XX',
  'sf_i18n_source' => 'XLIFF',
  'sf_i18n_debug' => false,
  'sf_i18n_cache' => true,
  'sf_i18n_untranslated_prefix' => '[T]',
  'sf_i18n_untranslated_suffix' => '[/T]',
));
