<?php
// auto-generated by sfViewConfigHandler
// date: 2008/04/01 14:44:00
$context  = $this->getContext();
$response = $context->getResponse();


  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!$context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'ullFlow', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'ullright is an opensource web framework initiated by ull.at business websolutions', false, false);
  $response->addMeta('keywords', 'ullright ull.at business websolutions workflow management open source', false, false);

  $response->addStylesheet('/ullFlowPlugin/css/main.css', '', array ());


