<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2008/04/01 14:44:00
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
