<?php

/**
 * PluginUllNewsletterMailingListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllNewsletterMailingListTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllNewsletterMailingListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllNewsletterMailingList');
    }
}