<?php

/**
 * PluginUllNewsletterLayoutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllNewsletterLayoutTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllNewsletterLayoutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllNewsletterLayout');
    }
}