<?php

/**
 * PluginUllNewsletterMailingList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginUllNewsletterMailingList extends BaseUllNewsletterMailingList
{
  /**
   * Unsubscribe the given users from the current list
   * 
   * @param mixed $users (record or record collection)
   * 
   * @return integer The number of unsubscribed entries
   */
  public function unsubscribeUsers($users)
  {
    $userIds = array();
    
    if ($users instanceof Doctrine_Record) //single user?
    {
      $userIds[] = $users['id'];
    }
    else //record collection
    {
      foreach ($users as $user)
      {
        $userIds[] = $user['id'];
      }
    }
    
    $q = new Doctrine_Query;
    $q
      ->delete('UllNewsletterMailingListSubscriber s')
      ->whereIn('s.ull_user_id', $userIds)
      ->addWhere('s.ull_newsletter_mailing_list_id = ?', $this['id'])
    ;
    
    return $q->execute();
  }
  
}