<?php

/**
 * PluginUllNewsletterCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllNewsletterCategoryTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllNewsletterCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllNewsletterCategory');
    }
}