<?php

/**
 * PluginUllNewsletterMailingListSubscriberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllNewsletterMailingListSubscriberTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllNewsletterMailingListSubscriberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllNewsletterMailingListSubscriber');
    }
}