<?php

/**
 * PluginUllNewsletterSubscriberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllNewsletterSubscriberTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllNewsletterSubscriberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllNewsletterSubscriber');
    }
}