<?php

/**
 * PluginUllMailErrorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllMailErrorTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllMailErrorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllMailError');
    }
}