<?php

/**
 * PluginUllNewsletterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllNewsletterTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllNewsletterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllNewsletter');
    }
}