<?php

/**
 * PluginUllMailQueuedMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllMailQueuedMessageTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllMailQueuedMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllMailQueuedMessage');
    }
}