<?php

/**
 * PluginUllNewsletterEditionMailingListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllNewsletterEditionMailingListTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllNewsletterEditionMailingListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllNewsletterEditionMailingList');
    }
}