<?php

/**
 * PluginUllMailMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllMailMessageTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllMailMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllMailMessage');
    }
    
    
    /**
     * Query messages to send from queue
     * 
     * @return object Doctrine_Query
     * 
     */
    public static function querySpooledMessages()
    {
      $q = new Doctrine_Query;
      $q
        ->from('UllMailMessage e')
        ->where('is_sent = ?', false)
      ;
      
      return $q;
    }    
}