<?php

/**
 * PluginUllNewsletterEdition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginUllNewsletterEdition extends BaseUllNewsletterEdition
{
  
  /**
   * Decorate the body with the selected template
   * 
   * @return string
   */
  public function getDecoratedBody()
  {
    $body = $this['body'];
    $layout = $this['UllNewsletterLayout']['html_layout'];
    
    $body = strtr($layout, array('[CONTENT]' => $body));
    
    return $body; 
  }
  
  
  /**
   * Get query for a list of recipients
   * 
   * @return Doctrine_Query
   */
  public function queryRecipients()
  {
    $q = new Doctrine_Query;
    $q
      ->select('DISTINCT u.email')
      ->from('UllUser u, u.UllUserStatus s, u.UllNewsletterMailingList ml, ml.UllNewsletterEdition e')
      ->addWhere('s.is_active = ?', true)
      ->addWhere('e.id = ?', $this->id)
      ->addWhere('u.email IS NOT NULL')
      ->addWhere('u.email <> ?', '')
      ->addOrderBy('u.email')
    ;
    
    return $q;
  }  
  
  
  /**
   * Return number of recipients
   * 
   * @return integer
   */
  public function countRecipients()
  {
    $q = $this->queryRecipients();
    
    return $q->count();
  }
  
  
  /**
   * Get a list of recipients
   * 
   * @return Doctrine_Collection
   */
  public function findRecipients($hydrationMode = null)
  {
    $q = $this->queryRecipients();
    
    return $q->execute(array(), $hydrationMode);
  }
  

  
  /**
   * Get mailing lists for the current edition and the given user
   * 
   * @param integer $ullUserId
   * 
   * @return Doctrine_Collection
   */
  public function findMailingListsForUser($ullUserId)
  {
    $q = new Doctrine_Query;
    $q
      ->select('ml.id, ml.name')
      ->from('UllNewsletterMailingList ml, ml.Subscribers u, u.UllUserStatus s, ml.UllNewsletterEdition e')
      ->addWhere('s.is_active = ?', true)
      ->addWhere('e.id = ?', $this->id)
      ->addWhere('u.id = ?', $ullUserId)
      ->addOrderBy('ml.name')
    ;
    
    return $q->execute();
  }  
  
  /**
   * Create message from the current newletter edition record
   * 
   * @param UllUser $loggedInUser
   * 
   * @return ullsfMail
   */
  public function createMailMessage(UllUser $loggedInUser)
  {
    $mail = new ullsfMail();
    
//    $mail->setFrom($loggedInUser['email'], $loggedInUser['display_name']);
    $mail->setFrom(array(
        sfConfig::get('app_ull_newsletter_from_address') =>
          sfConfig::get('app_ull_newsletter_from_name')
    ));
    
    $mail->setSubject($this['subject']);
    $mail->setHtmlBody($this->getDecoratedBody());
    
    $mail->setNewsletterEditionId($this['id']);
    
    $mail->setReturnPath(sfConfig::get('app_ull_newsletter_bounce_mail_box'));
    
    return $mail;
  }
  
}
