<?php

/**
 * PluginUllNewsletterEdition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginUllNewsletterEdition extends BaseUllNewsletterEdition
{
  
  /**
   * Decorate the body with the selected template
   * 
   * @return string
   */
  public function getDecoratedBody()
  {
    $body = $this['body'];
    $layout = $this['UllNewsletterLayout']['html_layout'];
    
    $body = strtr($layout, array('[CONTENT]' => $body));
    
    return $body; 
  }
  
  /**
   * Get a list of recipients
   * 
   * @return Doctrine_Collection
   */
  public function getRecipients($hydrationMode = null)
  {
    $q = new Doctrine_Query;
    $q
      ->select('DISTINCT u.email')
      ->from('UllUser u, u.UllUserStatus s, u.UllNewsletterMailingList ml, ml.UllNewsletterEdition e')
      ->addWhere('s.is_active = ?', true)
      ->addWhere('e.id = ?', $this->id)
      ->addOrderBy('u.email')
    ;
    
    return $q->execute(array(), $hydrationMode);
  }
  
  /**
   * Get mailing lists for the current edition and the given user
   * 
   * @param integer $ullUserId
   * 
   * @return Doctrine_Collection
   */
  public function getMailingListsForUser($ullUserId)
  {
    $q = new Doctrine_Query;
    $q
      ->select('ml.id, ml.name')
      ->from('UllNewsletterMailingList ml, ml.Subscribers u, u.UllUserStatus s, ml.UllNewsletterEdition e')
      ->addWhere('s.is_active = ?', true)
      ->addWhere('e.id = ?', $this->id)
      ->addWhere('u.id = ?', $ullUserId)
      ->addOrderBy('ml.name')
    ;
    
    return $q->execute();
  }  
  
}
