<?php

/**
 * PluginUllNewsletterInstanceCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllNewsletterInstanceCategoryTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllNewsletterInstanceCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllNewsletterInstanceCategory');
    }
}