<?php

/**
 * PluginUllMailLoggedMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUllMailLoggedMessageTable extends UllRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUllMailLoggedMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUllMailLoggedMessage');
    }
}