<?php
// auto-generated by sfPropelCrud
// date: 2007/11/20 08:53:43
?>
<?php

/**
 * text actions.
 *
 * @package    ull_at
 * @subpackage text
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class ullTextActions extends sfActions
{
  
  public function executeChange_culture() {
    
    $culture = $this->getRequestParameter('culture');
    $this->getUser()->setCulture($culture);     
    $this->redirect($this->getUser()->getAttribute('referer'));
      
  }
}
