# add additional entity (=users) columns here
#UllEntity:
#  package: ullCorePlugin.lib.model.doctrine
#  inheritance: 
#    extends: UllParentEntity
#    type: concrete
#  insert your custom columns here...    
#  columns:
#    my_custom_col1:
#      type: string(32)

# The cmd task doctrine:generate-migrations-diff does not work without a local 
# (= non-plugin) model
UselessTableForDoctrineMigrationsDiff:
  columns:
    foo:
      type: string(32)    