<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2008/04/01 08:31:30

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'hostspec' => 'localhost',
  'database' => 'ullright',
  'username' => 'ullright',
  'password' => 'right&wrong!',
  'port' => 3306,
  'persistant' => true,
), 'propel');
$this->databases['propel'] = $database;
